/**
 * Regenerates `app/packages/ui/src/i18n/plugin-strings.gen.ts` from the plugin
 * registry, so `gt translate` can extract plugin-provided UI strings (display
 * names, resource type labels, field/output labels, descriptions) into both
 * apps' translation catalogs.
 *
 * Plugin metadata is data shared with the server, CLI and API, so the plugin
 * packages themselves are never marked up for translation. Instead this
 * manifest feeds the CLI, and the UI translates the *values* at render time
 * through gt-react's runtime content hashing — the hash of a rendered data
 * string matches the hash extracted here as long as the text is identical,
 * which this generator guarantees by reading the same registry the server
 * ships. Run it (and commit the result) whenever plugin metadata changes:
 *
 *   pnpm --filter @infrawrench/web generate:plugin-strings
 *
 * `pnpm --filter @infrawrench/web translate` runs it automatically first.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { BUNDLED_PLUGINS } from "@infrawrench/server-core/plugin-loader";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, "../../ui/src/i18n/plugin-strings.gen.ts");

const strings = new Set<string>();
const add = (value: string | undefined) => {
  if (!value || !value.trim()) return;
  // Braces read as ICU variables and angle brackets as ICU tags to gt, so a
  // data string containing either could never round-trip cleanly ("{account}"
  // fails interpolation at render, "<registry>" fails ICU validation at
  // extraction). Both only occur in technical id-format descriptions that
  // shouldn't be translated anyway — leave them out of the catalog.
  if (/[{}<>]/.test(value)) return;
  strings.add(value);
};

for (const plugin of BUNDLED_PLUGINS) {
  const manifest = plugin.manifest;
  add(manifest.displayName);
  add(manifest.description);
  for (const field of manifest.credentialFields) {
    add(field.label);
    add(field.description);
    add(field.helpLink?.label);
    for (const region of field.regions ?? []) {
      add(region.label);
      add(region.location);
    }
  }
  for (const type of plugin.resourceTypes) {
    add(type.displayName);
    add(type.pluralDisplayName);
    add(type.description);
    for (const field of type.fields) {
      add(field.label);
      add(field.description);
    }
    for (const output of type.outputs) {
      add(output.label);
      add(output.description);
    }
  }
}

const sorted = [...strings].sort((a, b) => a.localeCompare(b, "en"));

const header = `/**
 * AUTO-GENERATED by \`pnpm --filter @infrawrench/web generate:plugin-strings\`
 * — do not edit by hand; edit the plugin metadata and regenerate.
 *
 * Extraction fodder for the gt CLI: every user-visible string the bundled
 * plugins contribute (display names, resource type labels, field and output
 * labels, descriptions), marked with msg() so \`gt translate\` puts them in the
 * catalogs. The module is never imported at runtime — the UI translates the
 * plugin *data* it receives by content hash, which matches these sources.
 */
import { msg } from "gt-react";

export const PLUGIN_STRINGS: readonly string[] = [
`;

const body = sorted.map((s) => `  msg(${JSON.stringify(s)}),`).join("\n");
writeFileSync(OUTPUT, `${header}${body}\n];\n`);
console.log(`[generate-plugin-strings] wrote ${sorted.length} strings to ${OUTPUT}`);
