/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardIdRouteImport } from './routes/dashboard.$dashboardId'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as ResourceAccountIdResourceIdRouteImport } from './routes/resource.$accountId.$resourceId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIdRoute = DashboardDashboardIdRouteImport.update({
  id: '/dashboard/$dashboardId',
  path: '/dashboard/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceAccountIdResourceIdRoute =
  ResourceAccountIdResourceIdRouteImport.update({
    id: '/resource/$accountId/$resourceId',
    path: '/resource/$accountId/$resourceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/changes': typeof ChangesRoute
  '/chat': typeof ChatRoute
  '/costs': typeof CostsRoute
  '/deployments': typeof DeploymentsRoute
  '/graph': typeof GraphRoute
  '/savings': typeof SavingsRoute
  '/workflows': typeof WorkflowsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/resource/$accountId/$resourceId': typeof ResourceAccountIdResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/changes': typeof ChangesRoute
  '/chat': typeof ChatRoute
  '/costs': typeof CostsRoute
  '/deployments': typeof DeploymentsRoute
  '/graph': typeof GraphRoute
  '/savings': typeof SavingsRoute
  '/workflows': typeof WorkflowsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/resource/$accountId/$resourceId': typeof ResourceAccountIdResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/changes': typeof ChangesRoute
  '/chat': typeof ChatRoute
  '/costs': typeof CostsRoute
  '/deployments': typeof DeploymentsRoute
  '/graph': typeof GraphRoute
  '/savings': typeof SavingsRoute
  '/workflows': typeof WorkflowsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/dashboard/$dashboardId': typeof DashboardDashboardIdRoute
  '/resource/$accountId/$resourceId': typeof ResourceAccountIdResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/changes'
    | '/chat'
    | '/costs'
    | '/deployments'
    | '/graph'
    | '/savings'
    | '/workflows'
    | '/accounts/$accountId'
    | '/dashboard/$dashboardId'
    | '/resource/$accountId/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/changes'
    | '/chat'
    | '/costs'
    | '/deployments'
    | '/graph'
    | '/savings'
    | '/workflows'
    | '/accounts/$accountId'
    | '/dashboard/$dashboardId'
    | '/resource/$accountId/$resourceId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/changes'
    | '/chat'
    | '/costs'
    | '/deployments'
    | '/graph'
    | '/savings'
    | '/workflows'
    | '/accounts/$accountId'
    | '/dashboard/$dashboardId'
    | '/resource/$accountId/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChangesRoute: typeof ChangesRoute
  ChatRoute: typeof ChatRoute
  CostsRoute: typeof CostsRoute
  DeploymentsRoute: typeof DeploymentsRoute
  GraphRoute: typeof GraphRoute
  SavingsRoute: typeof SavingsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  DashboardDashboardIdRoute: typeof DashboardDashboardIdRoute
  ResourceAccountIdResourceIdRoute: typeof ResourceAccountIdResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$dashboardId': {
      id: '/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/dashboard/$dashboardId'
      preLoaderRoute: typeof DashboardDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$accountId/$resourceId': {
      id: '/resource/$accountId/$resourceId'
      path: '/resource/$accountId/$resourceId'
      fullPath: '/resource/$accountId/$resourceId'
      preLoaderRoute: typeof ResourceAccountIdResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChangesRoute: ChangesRoute,
  ChatRoute: ChatRoute,
  CostsRoute: CostsRoute,
  DeploymentsRoute: DeploymentsRoute,
  GraphRoute: GraphRoute,
  SavingsRoute: SavingsRoute,
  WorkflowsRoute: WorkflowsRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  DashboardDashboardIdRoute: DashboardDashboardIdRoute,
  ResourceAccountIdResourceIdRoute: ResourceAccountIdResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
