import type { ResourceTypeDefinition } from "@infrawrench/plugin-base";
import { f, o, rt } from "@infrawrench/plugin-base";

const ro = { required: false, editable: false } as const;
const num = (key: string, label: string) => f(key, label, { ...ro, kind: "number" });
const bool = (key: string, label: string) => f(key, label, { ...ro, kind: "boolean" });

export const ServerResourceType = rt({
  name: "Server",
  id: "nats-server",
  accountRoot: true,
  description:
    "The nats-server behind this monitoring endpoint: version, cluster, connections and subscriptions, traffic, slow consumers, routes, gateways and leaf nodes, JetStream usage against its limits, and health. The Metrics tab records connections, memory, CPU and JetStream storage.",
  fields: [
    f("serverName", "Server Name", ro),
    f("serverId", "Server ID", ro),
    f("version", "Version", ro),
    f("goVersion", "Go", ro),
    f("clientUrl", "Client Listener", ro),
    f("cluster", "Cluster", ro),
    f("health", "Health", ro),
    f("uptime", "Uptime", ro),
    f("start", "Started", ro),
    num("connections", "Connections"),
    num("maxConnections", "Max Connections"),
    num("totalConnections", "Connections Since Start"),
    num("subscriptions", "Subscriptions"),
    num("slowConsumers", "Slow Consumers"),
    num("inMsgs", "Messages In"),
    num("outMsgs", "Messages Out"),
    num("inBytes", "Bytes In"),
    num("outBytes", "Bytes Out"),
    num("memory", "Memory (bytes)"),
    num("cpu", "CPU (%)"),
    num("cores", "Cores"),
    num("maxPayload", "Max Payload (bytes)"),
    num("routes", "Routes"),
    num("gateways", "Gateways"),
    num("leafnodes", "Leaf Nodes"),
    bool("tlsRequired", "TLS Required"),
    bool("authRequired", "Auth Required"),
    f("tlsCertNotAfter", "TLS Certificate Expires", ro),
    bool("jetstream", "JetStream"),
    num("jsStorage", "JetStream Storage Used (bytes)"),
    num("jsMaxStorage", "JetStream Max Storage (bytes)"),
    num("jsMemory", "JetStream Memory Used (bytes)"),
    num("jsMaxMemory", "JetStream Max Memory (bytes)"),
    num("jsStreams", "Streams"),
    num("jsConsumers", "Consumers"),
    num("jsApiErrors", "JetStream API Errors"),
    f("configLoadTime", "Config Loaded", ro),
  ],
  outputs: [o("clientUrl", "Client URL (nats://)"), o("monitoringUrl", "Monitoring URL")],
  expiryFields: [
    {
      fieldKey: "tlsCertNotAfter",
      from: "expiry",
      kind: "tls-cert",
      label: "Server TLS certificate expires",
    },
  ],
  supportsMetrics: true,
  supportsDelete: false,
  iconKey: "server",
});

export const PeerResourceType = rt({
  name: "Peer",
  id: "nats-peer",
  description:
    "A route to another server in the cluster, a gateway to another cluster, or a leaf node connection: remote name, address, round trip time, traffic and subscriptions.",
  fields: [
    f("kind", "Kind", ro),
    f("name", "Remote", ro),
    f("address", "Address", ro),
    f("account", "Account", ro),
    f("rtt", "RTT", ro),
    num("inMsgs", "Messages In"),
    num("outMsgs", "Messages Out"),
    num("subscriptions", "Subscriptions"),
    bool("solicited", "Outbound"),
  ],
  pinnable: false,
  iconKey: "link",
});

export const AccountResourceType = rt({
  name: "Account",
  id: "nats-account",
  description:
    "A NATS account: connections, leaf nodes, subscriptions, messages sent and received, slow consumers, and its JetStream storage, memory, streams and consumers.",
  fields: [
    f("name", "Name", ro),
    bool("system", "System Account"),
    num("connections", "Connections"),
    num("totalConnections", "Total Connections"),
    num("leafnodes", "Leaf Nodes"),
    num("subscriptions", "Subscriptions"),
    num("sentMsgs", "Messages Sent"),
    num("receivedMsgs", "Messages Received"),
    num("sentBytes", "Bytes Sent"),
    num("receivedBytes", "Bytes Received"),
    num("slowConsumers", "Slow Consumers"),
    num("jsStorage", "JetStream Storage (bytes)"),
    num("jsMemory", "JetStream Memory (bytes)"),
    num("streams", "Streams"),
    num("consumers", "Consumers"),
  ],
  supportsMetrics: true,
  iconKey: "users",
});

export const StreamResourceType = rt({
  name: "Stream",
  id: "nats-stream",
  parentTypeId: "nats-account",
  showInSidebar: true,
  description:
    "A JetStream stream (or a key-value bucket or object store, which are streams underneath): subjects, retention, storage, replicas and limits, messages, bytes, sequence range, and its cluster leader.",
  fields: [
    f("account", "Account", ro),
    f("name", "Name", ro),
    f("kind", "Kind", ro),
    f("description", "Description", ro),
    f("subjects", "Subjects", ro),
    f("retention", "Retention", ro),
    f("storage", "Storage", ro),
    num("replicas", "Replicas"),
    f("discard", "Discard", ro),
    num("maxMsgs", "Max Messages"),
    num("maxBytes", "Max Bytes"),
    num("maxAgeSeconds", "Max Age (s)"),
    num("maxMsgsPerSubject", "Max Per Subject"),
    num("maxMsgSize", "Max Message Size"),
    num("duplicateWindowSeconds", "Duplicate Window (s)"),
    f("compression", "Compression", ro),
    bool("sealed", "Sealed"),
    bool("denyDelete", "Deny Delete"),
    bool("denyPurge", "Deny Purge"),
    num("messages", "Messages"),
    num("bytes", "Bytes"),
    num("firstSeq", "First Sequence"),
    num("lastSeq", "Last Sequence"),
    f("lastTs", "Last Message", ro),
    num("subjectCount", "Subjects In Use"),
    num("consumers", "Consumers"),
    f("leader", "Leader", ro),
    f("created", "Created", ro),
  ],
  outputs: [o("name", "Stream name")],
  postureChecks: [
    {
      id: "nats-stream-single-replica",
      title: "Stream has a single replica",
      severity: "low",
      category: "data-protection",
      conditions: [{ fieldKey: "replicas", when: "equals", value: "1" }],
      reason: "A stream with one replica loses its messages if that server's storage is lost.",
    },
  ],
  supportsMetrics: true,
  iconKey: "database",
});

export const ConsumerResourceType = rt({
  name: "Consumer",
  id: "nats-consumer",
  parentTypeId: "nats-stream",
  showInSidebar: true,
  description:
    "A JetStream consumer: push or pull, deliver and ack policies, filter subjects, and its progress (pending, waiting for ack, redelivered, delivered and acknowledged sequences).",
  fields: [
    f("account", "Account", ro),
    f("stream", "Stream", ro),
    f("name", "Name", ro),
    bool("durable", "Durable"),
    f("mode", "Mode", ro),
    f("deliverPolicy", "Deliver Policy", ro),
    f("ackPolicy", "Ack Policy", ro),
    num("ackWaitSeconds", "Ack Wait (s)"),
    num("maxDeliver", "Max Deliver"),
    num("maxAckPending", "Max Ack Pending"),
    f("filterSubjects", "Filter Subjects", ro),
    f("deliverSubject", "Deliver Subject", ro),
    f("replayPolicy", "Replay Policy", ro),
    num("pending", "Pending"),
    num("ackPending", "Waiting For Ack"),
    num("redelivered", "Redelivered"),
    num("waiting", "Waiting Pulls"),
    num("deliveredStreamSeq", "Delivered (stream seq)"),
    num("ackFloorStreamSeq", "Ack Floor (stream seq)"),
    f("lastActive", "Last Active", ro),
    bool("pushBound", "Push Bound"),
    f("created", "Created", ro),
  ],
  pinnable: false,
  supportsMetrics: true,
  iconKey: "inbox",
});

export const ConnectionResourceType = rt({
  name: "Connection",
  id: "nats-connection",
  description:
    "An open client connection: name, address, account and user, client library and version, uptime, idle time, round trip, subscriptions, traffic and bytes pending.",
  fields: [
    num("cid", "Connection ID"),
    f("name", "Name", ro),
    f("address", "Client Address", ro),
    f("account", "Account", ro),
    f("user", "User", ro),
    f("client", "Client", ro),
    f("kind", "Kind", ro),
    f("uptime", "Uptime", ro),
    f("idle", "Idle", ro),
    f("rtt", "RTT", ro),
    num("subscriptions", "Subscriptions"),
    num("inMsgs", "Messages In"),
    num("outMsgs", "Messages Out"),
    num("pendingBytes", "Bytes Pending"),
    f("tls", "TLS", ro),
  ],
  dependsOn: [
    { fieldKey: "account", targetTypeId: "nats-account", targetKey: "name", label: "in" },
  ],
  pinnable: false,
  iconKey: "plug",
});

export const RESOURCE_TYPES: ResourceTypeDefinition[] = [
  ServerResourceType,
  PeerResourceType,
  AccountResourceType,
  StreamResourceType,
  ConsumerResourceType,
  ConnectionResourceType,
];
