import { f, o, rt } from "@infrawrench/plugin-base";

export const RouterResourceType = rt({
  name: "Router",
  id: "router",
  description:
    "A traffic router that spreads requests for one model string across several deployments",
  fields: [
    f("displayName", "Display Name", { required: false }),
    f("routerId", "Router ID", { editable: false }),
    f("state", "State", { required: false, editable: false }),
    f("statusMessage", "Status Message", { required: false, editable: false }),
    f("model", "Model", { required: false, editable: false }),
    f("deployments", "Deployments", { required: false, editable: false }),
    f("strategy", "Routing Strategy", {
      kind: "enum",
      enumValues: ["weightedRandom", "evenLoad"],
      required: false,
      description:
        "weightedRandom weights each deployment by its replica count; evenLoad keeps per-replica load balanced across deployments.",
    }),
    f("public", "Public", {
      kind: "boolean",
      required: false,
      description: "When on, any Fireworks account can query the workload behind this router.",
    }),
    f("aliases", "Aliases", { required: false, editable: false }),
    f("autoGenerated", "System-generated", { kind: "boolean", required: false, editable: false }),
    f("createdBy", "Created By", { required: false, editable: false }),
    f("createTime", "Created", { required: false, editable: false }),
  ],
  outputs: [
    o("routerName", "Router Resource Name", {
      description: "`accounts/{account}/routers/{id}`: pass this as `model` to route through it",
    }),
    o("routerId", "Router ID"),
  ],
  // `model` is a full resource name; `deployments` is a list and therefore not
  // a single-valued edge.
  dependsOn: [
    { fieldKey: "model", targetTypeId: "model", targetKey: "modelName", label: "routes" },
  ],
  supportsCreate: true,
  supportsUpdate: true,
  iconKey: "router",
});
