/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DeploySplatRouteImport } from './routes/deploy.$'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OrgOrgIdRouteImport } from './routes/org.$orgId'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as StatusSlugRouteImport } from './routes/status.$slug'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org.$orgId.index'
import { Route as OrgOrgIdAccessReviewRouteImport } from './routes/org.$orgId.access-review'
import { Route as OrgOrgIdAgentsRouteImport } from './routes/org.$orgId.agents'
import { Route as OrgOrgIdBackupsRouteImport } from './routes/org.$orgId.backups'
import { Route as OrgOrgIdChangesRouteImport } from './routes/org.$orgId.changes'
import { Route as OrgOrgIdChatRouteImport } from './routes/org.$orgId.chat'
import { Route as OrgOrgIdCostReportsRouteImport } from './routes/org.$orgId.cost-reports'
import { Route as OrgOrgIdCostsRouteImport } from './routes/org.$orgId.costs'
import { Route as OrgOrgIdDeploymentsRouteImport } from './routes/org.$orgId.deployments'
import { Route as OrgOrgIdDnsRouteImport } from './routes/org.$orgId.dns'
import { Route as OrgOrgIdEnvironmentDiffRouteImport } from './routes/org.$orgId.environment-diff'
import { Route as OrgOrgIdEnvironmentsRouteImport } from './routes/org.$orgId.environments'
import { Route as OrgOrgIdExpiringRouteImport } from './routes/org.$orgId.expiring'
import { Route as OrgOrgIdGraphRouteImport } from './routes/org.$orgId.graph'
import { Route as OrgOrgIdIacRouteImport } from './routes/org.$orgId.iac'
import { Route as OrgOrgIdIncidentsRouteImport } from './routes/org.$orgId.incidents'
import { Route as OrgOrgIdInvoicesRouteImport } from './routes/org.$orgId.invoices'
import { Route as OrgOrgIdLogsRouteImport } from './routes/org.$orgId.logs'
import { Route as OrgOrgIdMetricAlertsRouteImport } from './routes/org.$orgId.metric-alerts'
import { Route as OrgOrgIdMomentRouteImport } from './routes/org.$orgId.moment'
import { Route as OrgOrgIdPostureRouteImport } from './routes/org.$orgId.posture'
import { Route as OrgOrgIdProbesRouteImport } from './routes/org.$orgId.probes'
import { Route as OrgOrgIdQuotasRouteImport } from './routes/org.$orgId.quotas'
import { Route as OrgOrgIdSavingsRouteImport } from './routes/org.$orgId.savings'
import { Route as OrgOrgIdSettingsRouteImport } from './routes/org.$orgId.settings'
import { Route as OrgOrgIdSshFanoutRouteImport } from './routes/org.$orgId.ssh-fanout'
import { Route as OrgOrgIdStatusPagesRouteImport } from './routes/org.$orgId.status-pages'
import { Route as OrgOrgIdWorkflowsRouteImport } from './routes/org.$orgId.workflows'
import { Route as OrgOrgIdAccountsAccountIdRouteImport } from './routes/org.$orgId.accounts.$accountId'
import { Route as OrgOrgIdChatIndexRouteImport } from './routes/org.$orgId.chat.index'
import { Route as OrgOrgIdChatConversationIdRouteImport } from './routes/org.$orgId.chat.$conversationId'
import { Route as OrgOrgIdCostReportsReportIdRouteImport } from './routes/org.$orgId.cost-reports.$reportId'
import { Route as OrgOrgIdDashboardDashboardIdRouteImport } from './routes/org.$orgId.dashboard.$dashboardId'
import { Route as OrgOrgIdIncidentsIncidentIdRouteImport } from './routes/org.$orgId.incidents.$incidentId'
import { Route as OrgOrgIdInvoicesInvoiceIdRouteImport } from './routes/org.$orgId.invoices.$invoiceId'
import { Route as OrgOrgIdSettingsIndexRouteImport } from './routes/org.$orgId.settings.index'
import { Route as OrgOrgIdSettingsAccessRequestsRouteImport } from './routes/org.$orgId.settings.access-requests'
import { Route as OrgOrgIdSettingsAgentsRouteImport } from './routes/org.$orgId.settings.agents'
import { Route as OrgOrgIdSettingsApiKeysRouteImport } from './routes/org.$orgId.settings.api-keys'
import { Route as OrgOrgIdSettingsApprovalsRouteImport } from './routes/org.$orgId.settings.approvals'
import { Route as OrgOrgIdSettingsAuditLogRouteImport } from './routes/org.$orgId.settings.audit-log'
import { Route as OrgOrgIdSettingsBastionsRouteImport } from './routes/org.$orgId.settings.bastions'
import { Route as OrgOrgIdSettingsBillingRouteImport } from './routes/org.$orgId.settings.billing'
import { Route as OrgOrgIdSettingsBillingRulesRouteImport } from './routes/org.$orgId.settings.billing-rules'
import { Route as OrgOrgIdSettingsConfigRouteImport } from './routes/org.$orgId.settings.config'
import { Route as OrgOrgIdSettingsCostCentresRouteImport } from './routes/org.$orgId.settings.cost-centres'
import { Route as OrgOrgIdSettingsCostExportsRouteImport } from './routes/org.$orgId.settings.cost-exports'
import { Route as OrgOrgIdSettingsCredentialHygieneRouteImport } from './routes/org.$orgId.settings.credential-hygiene'
import { Route as OrgOrgIdSettingsCurrencyRouteImport } from './routes/org.$orgId.settings.currency'
import { Route as OrgOrgIdSettingsFreezesRouteImport } from './routes/org.$orgId.settings.freezes'
import { Route as OrgOrgIdSettingsJiraRouteImport } from './routes/org.$orgId.settings.jira'
import { Route as OrgOrgIdSettingsLinearRouteImport } from './routes/org.$orgId.settings.linear'
import { Route as OrgOrgIdSettingsPagingRouteImport } from './routes/org.$orgId.settings.paging'
import { Route as OrgOrgIdSettingsRolesRouteImport } from './routes/org.$orgId.settings.roles'
import { Route as OrgOrgIdSettingsSessionRecordingsRouteImport } from './routes/org.$orgId.settings.session-recordings'
import { Route as OrgOrgIdSettingsSshHostKeysRouteImport } from './routes/org.$orgId.settings.ssh-host-keys'
import { Route as OrgOrgIdSettingsSshKeysRouteImport } from './routes/org.$orgId.settings.ssh-keys'
import { Route as OrgOrgIdSettingsTagPolicyRouteImport } from './routes/org.$orgId.settings.tag-policy'
import { Route as OrgOrgIdSettingsTeamRouteImport } from './routes/org.$orgId.settings.team'
import { Route as OrgOrgIdWorkflowsWorkflowIdRouteImport } from './routes/org.$orgId.workflows.$workflowId'
import { Route as OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport } from './routes/org.$orgId.resources.$pluginId.$resourceTypeId.$resourceId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploySplatRoute = DeploySplatRouteImport.update({
  id: '/deploy/$',
  path: '/deploy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdAccessReviewRoute = OrgOrgIdAccessReviewRouteImport.update({
  id: '/access-review',
  path: '/access-review',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdAgentsRoute = OrgOrgIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdBackupsRoute = OrgOrgIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdChangesRoute = OrgOrgIdChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdChatRoute = OrgOrgIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdCostReportsRoute = OrgOrgIdCostReportsRouteImport.update({
  id: '/cost-reports',
  path: '/cost-reports',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdCostsRoute = OrgOrgIdCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdDeploymentsRoute = OrgOrgIdDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdDnsRoute = OrgOrgIdDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdEnvironmentDiffRoute = OrgOrgIdEnvironmentDiffRouteImport.update({
  id: '/environment-diff',
  path: '/environment-diff',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdEnvironmentsRoute = OrgOrgIdEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdExpiringRoute = OrgOrgIdExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdGraphRoute = OrgOrgIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdIacRoute = OrgOrgIdIacRouteImport.update({
  id: '/iac',
  path: '/iac',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdIncidentsRoute = OrgOrgIdIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdInvoicesRoute = OrgOrgIdInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdLogsRoute = OrgOrgIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdMetricAlertsRoute = OrgOrgIdMetricAlertsRouteImport.update({
  id: '/metric-alerts',
  path: '/metric-alerts',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdMomentRoute = OrgOrgIdMomentRouteImport.update({
  id: '/moment',
  path: '/moment',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdPostureRoute = OrgOrgIdPostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdProbesRoute = OrgOrgIdProbesRouteImport.update({
  id: '/probes',
  path: '/probes',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdQuotasRoute = OrgOrgIdQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSavingsRoute = OrgOrgIdSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsRoute = OrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSshFanoutRoute = OrgOrgIdSshFanoutRouteImport.update({
  id: '/ssh-fanout',
  path: '/ssh-fanout',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdStatusPagesRoute = OrgOrgIdStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdWorkflowsRoute = OrgOrgIdWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdAccountsAccountIdRoute =
  OrgOrgIdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdChatIndexRoute = OrgOrgIdChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdChatRoute,
} as any)
const OrgOrgIdChatConversationIdRoute =
  OrgOrgIdChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => OrgOrgIdChatRoute,
  } as any)
const OrgOrgIdCostReportsReportIdRoute =
  OrgOrgIdCostReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => OrgOrgIdCostReportsRoute,
  } as any)
const OrgOrgIdDashboardDashboardIdRoute =
  OrgOrgIdDashboardDashboardIdRouteImport.update({
    id: '/dashboard/$dashboardId',
    path: '/dashboard/$dashboardId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdIncidentsIncidentIdRoute =
  OrgOrgIdIncidentsIncidentIdRouteImport.update({
    id: '/$incidentId',
    path: '/$incidentId',
    getParentRoute: () => OrgOrgIdIncidentsRoute,
  } as any)
const OrgOrgIdInvoicesInvoiceIdRoute =
  OrgOrgIdInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => OrgOrgIdInvoicesRoute,
  } as any)
const OrgOrgIdSettingsIndexRoute = OrgOrgIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsAccessRequestsRoute =
  OrgOrgIdSettingsAccessRequestsRouteImport.update({
    id: '/access-requests',
    path: '/access-requests',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsAgentsRoute = OrgOrgIdSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsApiKeysRoute = OrgOrgIdSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsApprovalsRoute =
  OrgOrgIdSettingsApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsAuditLogRoute =
  OrgOrgIdSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsBastionsRoute =
  OrgOrgIdSettingsBastionsRouteImport.update({
    id: '/bastions',
    path: '/bastions',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsBillingRoute = OrgOrgIdSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsBillingRulesRoute =
  OrgOrgIdSettingsBillingRulesRouteImport.update({
    id: '/billing-rules',
    path: '/billing-rules',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsConfigRoute = OrgOrgIdSettingsConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsCostCentresRoute =
  OrgOrgIdSettingsCostCentresRouteImport.update({
    id: '/cost-centres',
    path: '/cost-centres',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsCostExportsRoute =
  OrgOrgIdSettingsCostExportsRouteImport.update({
    id: '/cost-exports',
    path: '/cost-exports',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsCredentialHygieneRoute =
  OrgOrgIdSettingsCredentialHygieneRouteImport.update({
    id: '/credential-hygiene',
    path: '/credential-hygiene',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsCurrencyRoute =
  OrgOrgIdSettingsCurrencyRouteImport.update({
    id: '/currency',
    path: '/currency',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsFreezesRoute = OrgOrgIdSettingsFreezesRouteImport.update({
  id: '/freezes',
  path: '/freezes',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsJiraRoute = OrgOrgIdSettingsJiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsLinearRoute = OrgOrgIdSettingsLinearRouteImport.update({
  id: '/linear',
  path: '/linear',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsPagingRoute = OrgOrgIdSettingsPagingRouteImport.update({
  id: '/paging',
  path: '/paging',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsRolesRoute = OrgOrgIdSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsSessionRecordingsRoute =
  OrgOrgIdSettingsSessionRecordingsRouteImport.update({
    id: '/session-recordings',
    path: '/session-recordings',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsSshHostKeysRoute =
  OrgOrgIdSettingsSshHostKeysRouteImport.update({
    id: '/ssh-host-keys',
    path: '/ssh-host-keys',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsSshKeysRoute = OrgOrgIdSettingsSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsTagPolicyRoute =
  OrgOrgIdSettingsTagPolicyRouteImport.update({
    id: '/tag-policy',
    path: '/tag-policy',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsTeamRoute = OrgOrgIdSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdWorkflowsWorkflowIdRoute =
  OrgOrgIdWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => OrgOrgIdWorkflowsRoute,
  } as any)
const OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute =
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport.update({
    id: '/resources/$pluginId/$resourceTypeId/$resourceId',
    path: '/resources/$pluginId/$resourceTypeId/$resourceId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/claim': typeof ClaimRoute
  '/onboarding': typeof OnboardingRoute
  '/deploy/$': typeof DeploySplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/org/$orgId/access-review': typeof OrgOrgIdAccessReviewRoute
  '/org/$orgId/agents': typeof OrgOrgIdAgentsRoute
  '/org/$orgId/backups': typeof OrgOrgIdBackupsRoute
  '/org/$orgId/changes': typeof OrgOrgIdChangesRoute
  '/org/$orgId/chat': typeof OrgOrgIdChatRouteWithChildren
  '/org/$orgId/cost-reports': typeof OrgOrgIdCostReportsRouteWithChildren
  '/org/$orgId/costs': typeof OrgOrgIdCostsRoute
  '/org/$orgId/deployments': typeof OrgOrgIdDeploymentsRoute
  '/org/$orgId/dns': typeof OrgOrgIdDnsRoute
  '/org/$orgId/environment-diff': typeof OrgOrgIdEnvironmentDiffRoute
  '/org/$orgId/environments': typeof OrgOrgIdEnvironmentsRoute
  '/org/$orgId/expiring': typeof OrgOrgIdExpiringRoute
  '/org/$orgId/graph': typeof OrgOrgIdGraphRoute
  '/org/$orgId/iac': typeof OrgOrgIdIacRoute
  '/org/$orgId/incidents': typeof OrgOrgIdIncidentsRouteWithChildren
  '/org/$orgId/invoices': typeof OrgOrgIdInvoicesRouteWithChildren
  '/org/$orgId/logs': typeof OrgOrgIdLogsRoute
  '/org/$orgId/metric-alerts': typeof OrgOrgIdMetricAlertsRoute
  '/org/$orgId/moment': typeof OrgOrgIdMomentRoute
  '/org/$orgId/posture': typeof OrgOrgIdPostureRoute
  '/org/$orgId/probes': typeof OrgOrgIdProbesRoute
  '/org/$orgId/quotas': typeof OrgOrgIdQuotasRoute
  '/org/$orgId/savings': typeof OrgOrgIdSavingsRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/ssh-fanout': typeof OrgOrgIdSshFanoutRoute
  '/org/$orgId/status-pages': typeof OrgOrgIdStatusPagesRoute
  '/org/$orgId/workflows': typeof OrgOrgIdWorkflowsRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/chat/$conversationId': typeof OrgOrgIdChatConversationIdRoute
  '/org/$orgId/cost-reports/$reportId': typeof OrgOrgIdCostReportsReportIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/incidents/$incidentId': typeof OrgOrgIdIncidentsIncidentIdRoute
  '/org/$orgId/invoices/$invoiceId': typeof OrgOrgIdInvoicesInvoiceIdRoute
  '/org/$orgId/settings/access-requests': typeof OrgOrgIdSettingsAccessRequestsRoute
  '/org/$orgId/settings/agents': typeof OrgOrgIdSettingsAgentsRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/approvals': typeof OrgOrgIdSettingsApprovalsRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/bastions': typeof OrgOrgIdSettingsBastionsRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/billing-rules': typeof OrgOrgIdSettingsBillingRulesRoute
  '/org/$orgId/settings/config': typeof OrgOrgIdSettingsConfigRoute
  '/org/$orgId/settings/cost-centres': typeof OrgOrgIdSettingsCostCentresRoute
  '/org/$orgId/settings/cost-exports': typeof OrgOrgIdSettingsCostExportsRoute
  '/org/$orgId/settings/credential-hygiene': typeof OrgOrgIdSettingsCredentialHygieneRoute
  '/org/$orgId/settings/currency': typeof OrgOrgIdSettingsCurrencyRoute
  '/org/$orgId/settings/freezes': typeof OrgOrgIdSettingsFreezesRoute
  '/org/$orgId/settings/jira': typeof OrgOrgIdSettingsJiraRoute
  '/org/$orgId/settings/linear': typeof OrgOrgIdSettingsLinearRoute
  '/org/$orgId/settings/paging': typeof OrgOrgIdSettingsPagingRoute
  '/org/$orgId/settings/roles': typeof OrgOrgIdSettingsRolesRoute
  '/org/$orgId/settings/session-recordings': typeof OrgOrgIdSettingsSessionRecordingsRoute
  '/org/$orgId/settings/ssh-host-keys': typeof OrgOrgIdSettingsSshHostKeysRoute
  '/org/$orgId/settings/ssh-keys': typeof OrgOrgIdSettingsSshKeysRoute
  '/org/$orgId/settings/tag-policy': typeof OrgOrgIdSettingsTagPolicyRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/workflows/$workflowId': typeof OrgOrgIdWorkflowsWorkflowIdRoute
  '/org/$orgId/chat/': typeof OrgOrgIdChatIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/claim': typeof ClaimRoute
  '/onboarding': typeof OnboardingRoute
  '/deploy/$': typeof DeploySplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/org/$orgId/access-review': typeof OrgOrgIdAccessReviewRoute
  '/org/$orgId/agents': typeof OrgOrgIdAgentsRoute
  '/org/$orgId/backups': typeof OrgOrgIdBackupsRoute
  '/org/$orgId/changes': typeof OrgOrgIdChangesRoute
  '/org/$orgId/cost-reports': typeof OrgOrgIdCostReportsRouteWithChildren
  '/org/$orgId/costs': typeof OrgOrgIdCostsRoute
  '/org/$orgId/deployments': typeof OrgOrgIdDeploymentsRoute
  '/org/$orgId/dns': typeof OrgOrgIdDnsRoute
  '/org/$orgId/environment-diff': typeof OrgOrgIdEnvironmentDiffRoute
  '/org/$orgId/environments': typeof OrgOrgIdEnvironmentsRoute
  '/org/$orgId/expiring': typeof OrgOrgIdExpiringRoute
  '/org/$orgId/graph': typeof OrgOrgIdGraphRoute
  '/org/$orgId/iac': typeof OrgOrgIdIacRoute
  '/org/$orgId/incidents': typeof OrgOrgIdIncidentsRouteWithChildren
  '/org/$orgId/invoices': typeof OrgOrgIdInvoicesRouteWithChildren
  '/org/$orgId/logs': typeof OrgOrgIdLogsRoute
  '/org/$orgId/metric-alerts': typeof OrgOrgIdMetricAlertsRoute
  '/org/$orgId/moment': typeof OrgOrgIdMomentRoute
  '/org/$orgId/posture': typeof OrgOrgIdPostureRoute
  '/org/$orgId/probes': typeof OrgOrgIdProbesRoute
  '/org/$orgId/quotas': typeof OrgOrgIdQuotasRoute
  '/org/$orgId/savings': typeof OrgOrgIdSavingsRoute
  '/org/$orgId/ssh-fanout': typeof OrgOrgIdSshFanoutRoute
  '/org/$orgId/status-pages': typeof OrgOrgIdStatusPagesRoute
  '/org/$orgId/workflows': typeof OrgOrgIdWorkflowsRouteWithChildren
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/chat/$conversationId': typeof OrgOrgIdChatConversationIdRoute
  '/org/$orgId/cost-reports/$reportId': typeof OrgOrgIdCostReportsReportIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/incidents/$incidentId': typeof OrgOrgIdIncidentsIncidentIdRoute
  '/org/$orgId/invoices/$invoiceId': typeof OrgOrgIdInvoicesInvoiceIdRoute
  '/org/$orgId/settings/access-requests': typeof OrgOrgIdSettingsAccessRequestsRoute
  '/org/$orgId/settings/agents': typeof OrgOrgIdSettingsAgentsRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/approvals': typeof OrgOrgIdSettingsApprovalsRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/bastions': typeof OrgOrgIdSettingsBastionsRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/billing-rules': typeof OrgOrgIdSettingsBillingRulesRoute
  '/org/$orgId/settings/config': typeof OrgOrgIdSettingsConfigRoute
  '/org/$orgId/settings/cost-centres': typeof OrgOrgIdSettingsCostCentresRoute
  '/org/$orgId/settings/cost-exports': typeof OrgOrgIdSettingsCostExportsRoute
  '/org/$orgId/settings/credential-hygiene': typeof OrgOrgIdSettingsCredentialHygieneRoute
  '/org/$orgId/settings/currency': typeof OrgOrgIdSettingsCurrencyRoute
  '/org/$orgId/settings/freezes': typeof OrgOrgIdSettingsFreezesRoute
  '/org/$orgId/settings/jira': typeof OrgOrgIdSettingsJiraRoute
  '/org/$orgId/settings/linear': typeof OrgOrgIdSettingsLinearRoute
  '/org/$orgId/settings/paging': typeof OrgOrgIdSettingsPagingRoute
  '/org/$orgId/settings/roles': typeof OrgOrgIdSettingsRolesRoute
  '/org/$orgId/settings/session-recordings': typeof OrgOrgIdSettingsSessionRecordingsRoute
  '/org/$orgId/settings/ssh-host-keys': typeof OrgOrgIdSettingsSshHostKeysRoute
  '/org/$orgId/settings/ssh-keys': typeof OrgOrgIdSettingsSshKeysRoute
  '/org/$orgId/settings/tag-policy': typeof OrgOrgIdSettingsTagPolicyRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/workflows/$workflowId': typeof OrgOrgIdWorkflowsWorkflowIdRoute
  '/org/$orgId/chat': typeof OrgOrgIdChatIndexRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/claim': typeof ClaimRoute
  '/onboarding': typeof OnboardingRoute
  '/deploy/$': typeof DeploySplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/org/$orgId/access-review': typeof OrgOrgIdAccessReviewRoute
  '/org/$orgId/agents': typeof OrgOrgIdAgentsRoute
  '/org/$orgId/backups': typeof OrgOrgIdBackupsRoute
  '/org/$orgId/changes': typeof OrgOrgIdChangesRoute
  '/org/$orgId/chat': typeof OrgOrgIdChatRouteWithChildren
  '/org/$orgId/cost-reports': typeof OrgOrgIdCostReportsRouteWithChildren
  '/org/$orgId/costs': typeof OrgOrgIdCostsRoute
  '/org/$orgId/deployments': typeof OrgOrgIdDeploymentsRoute
  '/org/$orgId/dns': typeof OrgOrgIdDnsRoute
  '/org/$orgId/environment-diff': typeof OrgOrgIdEnvironmentDiffRoute
  '/org/$orgId/environments': typeof OrgOrgIdEnvironmentsRoute
  '/org/$orgId/expiring': typeof OrgOrgIdExpiringRoute
  '/org/$orgId/graph': typeof OrgOrgIdGraphRoute
  '/org/$orgId/iac': typeof OrgOrgIdIacRoute
  '/org/$orgId/incidents': typeof OrgOrgIdIncidentsRouteWithChildren
  '/org/$orgId/invoices': typeof OrgOrgIdInvoicesRouteWithChildren
  '/org/$orgId/logs': typeof OrgOrgIdLogsRoute
  '/org/$orgId/metric-alerts': typeof OrgOrgIdMetricAlertsRoute
  '/org/$orgId/moment': typeof OrgOrgIdMomentRoute
  '/org/$orgId/posture': typeof OrgOrgIdPostureRoute
  '/org/$orgId/probes': typeof OrgOrgIdProbesRoute
  '/org/$orgId/quotas': typeof OrgOrgIdQuotasRoute
  '/org/$orgId/savings': typeof OrgOrgIdSavingsRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/ssh-fanout': typeof OrgOrgIdSshFanoutRoute
  '/org/$orgId/status-pages': typeof OrgOrgIdStatusPagesRoute
  '/org/$orgId/workflows': typeof OrgOrgIdWorkflowsRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/chat/$conversationId': typeof OrgOrgIdChatConversationIdRoute
  '/org/$orgId/cost-reports/$reportId': typeof OrgOrgIdCostReportsReportIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/incidents/$incidentId': typeof OrgOrgIdIncidentsIncidentIdRoute
  '/org/$orgId/invoices/$invoiceId': typeof OrgOrgIdInvoicesInvoiceIdRoute
  '/org/$orgId/settings/access-requests': typeof OrgOrgIdSettingsAccessRequestsRoute
  '/org/$orgId/settings/agents': typeof OrgOrgIdSettingsAgentsRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/approvals': typeof OrgOrgIdSettingsApprovalsRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/bastions': typeof OrgOrgIdSettingsBastionsRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/billing-rules': typeof OrgOrgIdSettingsBillingRulesRoute
  '/org/$orgId/settings/config': typeof OrgOrgIdSettingsConfigRoute
  '/org/$orgId/settings/cost-centres': typeof OrgOrgIdSettingsCostCentresRoute
  '/org/$orgId/settings/cost-exports': typeof OrgOrgIdSettingsCostExportsRoute
  '/org/$orgId/settings/credential-hygiene': typeof OrgOrgIdSettingsCredentialHygieneRoute
  '/org/$orgId/settings/currency': typeof OrgOrgIdSettingsCurrencyRoute
  '/org/$orgId/settings/freezes': typeof OrgOrgIdSettingsFreezesRoute
  '/org/$orgId/settings/jira': typeof OrgOrgIdSettingsJiraRoute
  '/org/$orgId/settings/linear': typeof OrgOrgIdSettingsLinearRoute
  '/org/$orgId/settings/paging': typeof OrgOrgIdSettingsPagingRoute
  '/org/$orgId/settings/roles': typeof OrgOrgIdSettingsRolesRoute
  '/org/$orgId/settings/session-recordings': typeof OrgOrgIdSettingsSessionRecordingsRoute
  '/org/$orgId/settings/ssh-host-keys': typeof OrgOrgIdSettingsSshHostKeysRoute
  '/org/$orgId/settings/ssh-keys': typeof OrgOrgIdSettingsSshKeysRoute
  '/org/$orgId/settings/tag-policy': typeof OrgOrgIdSettingsTagPolicyRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/workflows/$workflowId': typeof OrgOrgIdWorkflowsWorkflowIdRoute
  '/org/$orgId/chat/': typeof OrgOrgIdChatIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/claim'
    | '/onboarding'
    | '/deploy/$'
    | '/invite/$token'
    | '/org/$orgId'
    | '/share/$token'
    | '/status/$slug'
    | '/org/$orgId/access-review'
    | '/org/$orgId/agents'
    | '/org/$orgId/backups'
    | '/org/$orgId/changes'
    | '/org/$orgId/chat'
    | '/org/$orgId/cost-reports'
    | '/org/$orgId/costs'
    | '/org/$orgId/deployments'
    | '/org/$orgId/dns'
    | '/org/$orgId/environment-diff'
    | '/org/$orgId/environments'
    | '/org/$orgId/expiring'
    | '/org/$orgId/graph'
    | '/org/$orgId/iac'
    | '/org/$orgId/incidents'
    | '/org/$orgId/invoices'
    | '/org/$orgId/logs'
    | '/org/$orgId/metric-alerts'
    | '/org/$orgId/moment'
    | '/org/$orgId/posture'
    | '/org/$orgId/probes'
    | '/org/$orgId/quotas'
    | '/org/$orgId/savings'
    | '/org/$orgId/settings'
    | '/org/$orgId/ssh-fanout'
    | '/org/$orgId/status-pages'
    | '/org/$orgId/workflows'
    | '/org/$orgId/'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/chat/$conversationId'
    | '/org/$orgId/cost-reports/$reportId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/incidents/$incidentId'
    | '/org/$orgId/invoices/$invoiceId'
    | '/org/$orgId/settings/access-requests'
    | '/org/$orgId/settings/agents'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/approvals'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/bastions'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/billing-rules'
    | '/org/$orgId/settings/config'
    | '/org/$orgId/settings/cost-centres'
    | '/org/$orgId/settings/cost-exports'
    | '/org/$orgId/settings/credential-hygiene'
    | '/org/$orgId/settings/currency'
    | '/org/$orgId/settings/freezes'
    | '/org/$orgId/settings/jira'
    | '/org/$orgId/settings/linear'
    | '/org/$orgId/settings/paging'
    | '/org/$orgId/settings/roles'
    | '/org/$orgId/settings/session-recordings'
    | '/org/$orgId/settings/ssh-host-keys'
    | '/org/$orgId/settings/ssh-keys'
    | '/org/$orgId/settings/tag-policy'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/workflows/$workflowId'
    | '/org/$orgId/chat/'
    | '/org/$orgId/settings/'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/claim'
    | '/onboarding'
    | '/deploy/$'
    | '/invite/$token'
    | '/share/$token'
    | '/status/$slug'
    | '/org/$orgId/access-review'
    | '/org/$orgId/agents'
    | '/org/$orgId/backups'
    | '/org/$orgId/changes'
    | '/org/$orgId/cost-reports'
    | '/org/$orgId/costs'
    | '/org/$orgId/deployments'
    | '/org/$orgId/dns'
    | '/org/$orgId/environment-diff'
    | '/org/$orgId/environments'
    | '/org/$orgId/expiring'
    | '/org/$orgId/graph'
    | '/org/$orgId/iac'
    | '/org/$orgId/incidents'
    | '/org/$orgId/invoices'
    | '/org/$orgId/logs'
    | '/org/$orgId/metric-alerts'
    | '/org/$orgId/moment'
    | '/org/$orgId/posture'
    | '/org/$orgId/probes'
    | '/org/$orgId/quotas'
    | '/org/$orgId/savings'
    | '/org/$orgId/ssh-fanout'
    | '/org/$orgId/status-pages'
    | '/org/$orgId/workflows'
    | '/org/$orgId'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/chat/$conversationId'
    | '/org/$orgId/cost-reports/$reportId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/incidents/$incidentId'
    | '/org/$orgId/invoices/$invoiceId'
    | '/org/$orgId/settings/access-requests'
    | '/org/$orgId/settings/agents'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/approvals'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/bastions'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/billing-rules'
    | '/org/$orgId/settings/config'
    | '/org/$orgId/settings/cost-centres'
    | '/org/$orgId/settings/cost-exports'
    | '/org/$orgId/settings/credential-hygiene'
    | '/org/$orgId/settings/currency'
    | '/org/$orgId/settings/freezes'
    | '/org/$orgId/settings/jira'
    | '/org/$orgId/settings/linear'
    | '/org/$orgId/settings/paging'
    | '/org/$orgId/settings/roles'
    | '/org/$orgId/settings/session-recordings'
    | '/org/$orgId/settings/ssh-host-keys'
    | '/org/$orgId/settings/ssh-keys'
    | '/org/$orgId/settings/tag-policy'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/workflows/$workflowId'
    | '/org/$orgId/chat'
    | '/org/$orgId/settings'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  id:
    | '__root__'
    | '/admin'
    | '/claim'
    | '/onboarding'
    | '/deploy/$'
    | '/invite/$token'
    | '/org/$orgId'
    | '/share/$token'
    | '/status/$slug'
    | '/org/$orgId/access-review'
    | '/org/$orgId/agents'
    | '/org/$orgId/backups'
    | '/org/$orgId/changes'
    | '/org/$orgId/chat'
    | '/org/$orgId/cost-reports'
    | '/org/$orgId/costs'
    | '/org/$orgId/deployments'
    | '/org/$orgId/dns'
    | '/org/$orgId/environment-diff'
    | '/org/$orgId/environments'
    | '/org/$orgId/expiring'
    | '/org/$orgId/graph'
    | '/org/$orgId/iac'
    | '/org/$orgId/incidents'
    | '/org/$orgId/invoices'
    | '/org/$orgId/logs'
    | '/org/$orgId/metric-alerts'
    | '/org/$orgId/moment'
    | '/org/$orgId/posture'
    | '/org/$orgId/probes'
    | '/org/$orgId/quotas'
    | '/org/$orgId/savings'
    | '/org/$orgId/settings'
    | '/org/$orgId/ssh-fanout'
    | '/org/$orgId/status-pages'
    | '/org/$orgId/workflows'
    | '/org/$orgId/'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/chat/$conversationId'
    | '/org/$orgId/cost-reports/$reportId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/incidents/$incidentId'
    | '/org/$orgId/invoices/$invoiceId'
    | '/org/$orgId/settings/access-requests'
    | '/org/$orgId/settings/agents'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/approvals'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/bastions'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/billing-rules'
    | '/org/$orgId/settings/config'
    | '/org/$orgId/settings/cost-centres'
    | '/org/$orgId/settings/cost-exports'
    | '/org/$orgId/settings/credential-hygiene'
    | '/org/$orgId/settings/currency'
    | '/org/$orgId/settings/freezes'
    | '/org/$orgId/settings/jira'
    | '/org/$orgId/settings/linear'
    | '/org/$orgId/settings/paging'
    | '/org/$orgId/settings/roles'
    | '/org/$orgId/settings/session-recordings'
    | '/org/$orgId/settings/ssh-host-keys'
    | '/org/$orgId/settings/ssh-keys'
    | '/org/$orgId/settings/tag-policy'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/workflows/$workflowId'
    | '/org/$orgId/chat/'
    | '/org/$orgId/settings/'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  ClaimRoute: typeof ClaimRoute
  OnboardingRoute: typeof OnboardingRoute
  DeploySplatRoute: typeof DeploySplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
  StatusSlugRoute: typeof StatusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy/$': {
      id: '/deploy/$'
      path: '/deploy/$'
      fullPath: '/deploy/$'
      preLoaderRoute: typeof DeploySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/access-review': {
      id: '/org/$orgId/access-review'
      path: '/access-review'
      fullPath: '/org/$orgId/access-review'
      preLoaderRoute: typeof OrgOrgIdAccessReviewRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/agents': {
      id: '/org/$orgId/agents'
      path: '/agents'
      fullPath: '/org/$orgId/agents'
      preLoaderRoute: typeof OrgOrgIdAgentsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/backups': {
      id: '/org/$orgId/backups'
      path: '/backups'
      fullPath: '/org/$orgId/backups'
      preLoaderRoute: typeof OrgOrgIdBackupsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/changes': {
      id: '/org/$orgId/changes'
      path: '/changes'
      fullPath: '/org/$orgId/changes'
      preLoaderRoute: typeof OrgOrgIdChangesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/chat': {
      id: '/org/$orgId/chat'
      path: '/chat'
      fullPath: '/org/$orgId/chat'
      preLoaderRoute: typeof OrgOrgIdChatRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/cost-reports': {
      id: '/org/$orgId/cost-reports'
      path: '/cost-reports'
      fullPath: '/org/$orgId/cost-reports'
      preLoaderRoute: typeof OrgOrgIdCostReportsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/costs': {
      id: '/org/$orgId/costs'
      path: '/costs'
      fullPath: '/org/$orgId/costs'
      preLoaderRoute: typeof OrgOrgIdCostsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/deployments': {
      id: '/org/$orgId/deployments'
      path: '/deployments'
      fullPath: '/org/$orgId/deployments'
      preLoaderRoute: typeof OrgOrgIdDeploymentsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/dns': {
      id: '/org/$orgId/dns'
      path: '/dns'
      fullPath: '/org/$orgId/dns'
      preLoaderRoute: typeof OrgOrgIdDnsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/environment-diff': {
      id: '/org/$orgId/environment-diff'
      path: '/environment-diff'
      fullPath: '/org/$orgId/environment-diff'
      preLoaderRoute: typeof OrgOrgIdEnvironmentDiffRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/environments': {
      id: '/org/$orgId/environments'
      path: '/environments'
      fullPath: '/org/$orgId/environments'
      preLoaderRoute: typeof OrgOrgIdEnvironmentsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/expiring': {
      id: '/org/$orgId/expiring'
      path: '/expiring'
      fullPath: '/org/$orgId/expiring'
      preLoaderRoute: typeof OrgOrgIdExpiringRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/graph': {
      id: '/org/$orgId/graph'
      path: '/graph'
      fullPath: '/org/$orgId/graph'
      preLoaderRoute: typeof OrgOrgIdGraphRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/iac': {
      id: '/org/$orgId/iac'
      path: '/iac'
      fullPath: '/org/$orgId/iac'
      preLoaderRoute: typeof OrgOrgIdIacRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/incidents': {
      id: '/org/$orgId/incidents'
      path: '/incidents'
      fullPath: '/org/$orgId/incidents'
      preLoaderRoute: typeof OrgOrgIdIncidentsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/invoices': {
      id: '/org/$orgId/invoices'
      path: '/invoices'
      fullPath: '/org/$orgId/invoices'
      preLoaderRoute: typeof OrgOrgIdInvoicesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/logs': {
      id: '/org/$orgId/logs'
      path: '/logs'
      fullPath: '/org/$orgId/logs'
      preLoaderRoute: typeof OrgOrgIdLogsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/metric-alerts': {
      id: '/org/$orgId/metric-alerts'
      path: '/metric-alerts'
      fullPath: '/org/$orgId/metric-alerts'
      preLoaderRoute: typeof OrgOrgIdMetricAlertsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/moment': {
      id: '/org/$orgId/moment'
      path: '/moment'
      fullPath: '/org/$orgId/moment'
      preLoaderRoute: typeof OrgOrgIdMomentRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/posture': {
      id: '/org/$orgId/posture'
      path: '/posture'
      fullPath: '/org/$orgId/posture'
      preLoaderRoute: typeof OrgOrgIdPostureRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/probes': {
      id: '/org/$orgId/probes'
      path: '/probes'
      fullPath: '/org/$orgId/probes'
      preLoaderRoute: typeof OrgOrgIdProbesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/quotas': {
      id: '/org/$orgId/quotas'
      path: '/quotas'
      fullPath: '/org/$orgId/quotas'
      preLoaderRoute: typeof OrgOrgIdQuotasRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/savings': {
      id: '/org/$orgId/savings'
      path: '/savings'
      fullPath: '/org/$orgId/savings'
      preLoaderRoute: typeof OrgOrgIdSavingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings': {
      id: '/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof OrgOrgIdSettingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/ssh-fanout': {
      id: '/org/$orgId/ssh-fanout'
      path: '/ssh-fanout'
      fullPath: '/org/$orgId/ssh-fanout'
      preLoaderRoute: typeof OrgOrgIdSshFanoutRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/status-pages': {
      id: '/org/$orgId/status-pages'
      path: '/status-pages'
      fullPath: '/org/$orgId/status-pages'
      preLoaderRoute: typeof OrgOrgIdStatusPagesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/workflows': {
      id: '/org/$orgId/workflows'
      path: '/workflows'
      fullPath: '/org/$orgId/workflows'
      preLoaderRoute: typeof OrgOrgIdWorkflowsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/accounts/$accountId': {
      id: '/org/$orgId/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/org/$orgId/accounts/$accountId'
      preLoaderRoute: typeof OrgOrgIdAccountsAccountIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/chat/': {
      id: '/org/$orgId/chat/'
      path: '/'
      fullPath: '/org/$orgId/chat/'
      preLoaderRoute: typeof OrgOrgIdChatIndexRouteImport
      parentRoute: typeof OrgOrgIdChatRoute
    }
    '/org/$orgId/chat/$conversationId': {
      id: '/org/$orgId/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/org/$orgId/chat/$conversationId'
      preLoaderRoute: typeof OrgOrgIdChatConversationIdRouteImport
      parentRoute: typeof OrgOrgIdChatRoute
    }
    '/org/$orgId/cost-reports/$reportId': {
      id: '/org/$orgId/cost-reports/$reportId'
      path: '/$reportId'
      fullPath: '/org/$orgId/cost-reports/$reportId'
      preLoaderRoute: typeof OrgOrgIdCostReportsReportIdRouteImport
      parentRoute: typeof OrgOrgIdCostReportsRoute
    }
    '/org/$orgId/dashboard/$dashboardId': {
      id: '/org/$orgId/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/org/$orgId/dashboard/$dashboardId'
      preLoaderRoute: typeof OrgOrgIdDashboardDashboardIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/incidents/$incidentId': {
      id: '/org/$orgId/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/org/$orgId/incidents/$incidentId'
      preLoaderRoute: typeof OrgOrgIdIncidentsIncidentIdRouteImport
      parentRoute: typeof OrgOrgIdIncidentsRoute
    }
    '/org/$orgId/invoices/$invoiceId': {
      id: '/org/$orgId/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/org/$orgId/invoices/$invoiceId'
      preLoaderRoute: typeof OrgOrgIdInvoicesInvoiceIdRouteImport
      parentRoute: typeof OrgOrgIdInvoicesRoute
    }
    '/org/$orgId/settings/': {
      id: '/org/$orgId/settings/'
      path: '/'
      fullPath: '/org/$orgId/settings/'
      preLoaderRoute: typeof OrgOrgIdSettingsIndexRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/access-requests': {
      id: '/org/$orgId/settings/access-requests'
      path: '/access-requests'
      fullPath: '/org/$orgId/settings/access-requests'
      preLoaderRoute: typeof OrgOrgIdSettingsAccessRequestsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/agents': {
      id: '/org/$orgId/settings/agents'
      path: '/agents'
      fullPath: '/org/$orgId/settings/agents'
      preLoaderRoute: typeof OrgOrgIdSettingsAgentsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/api-keys': {
      id: '/org/$orgId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/org/$orgId/settings/api-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsApiKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/approvals': {
      id: '/org/$orgId/settings/approvals'
      path: '/approvals'
      fullPath: '/org/$orgId/settings/approvals'
      preLoaderRoute: typeof OrgOrgIdSettingsApprovalsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/audit-log': {
      id: '/org/$orgId/settings/audit-log'
      path: '/audit-log'
      fullPath: '/org/$orgId/settings/audit-log'
      preLoaderRoute: typeof OrgOrgIdSettingsAuditLogRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/bastions': {
      id: '/org/$orgId/settings/bastions'
      path: '/bastions'
      fullPath: '/org/$orgId/settings/bastions'
      preLoaderRoute: typeof OrgOrgIdSettingsBastionsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/billing': {
      id: '/org/$orgId/settings/billing'
      path: '/billing'
      fullPath: '/org/$orgId/settings/billing'
      preLoaderRoute: typeof OrgOrgIdSettingsBillingRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/billing-rules': {
      id: '/org/$orgId/settings/billing-rules'
      path: '/billing-rules'
      fullPath: '/org/$orgId/settings/billing-rules'
      preLoaderRoute: typeof OrgOrgIdSettingsBillingRulesRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/config': {
      id: '/org/$orgId/settings/config'
      path: '/config'
      fullPath: '/org/$orgId/settings/config'
      preLoaderRoute: typeof OrgOrgIdSettingsConfigRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/cost-centres': {
      id: '/org/$orgId/settings/cost-centres'
      path: '/cost-centres'
      fullPath: '/org/$orgId/settings/cost-centres'
      preLoaderRoute: typeof OrgOrgIdSettingsCostCentresRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/cost-exports': {
      id: '/org/$orgId/settings/cost-exports'
      path: '/cost-exports'
      fullPath: '/org/$orgId/settings/cost-exports'
      preLoaderRoute: typeof OrgOrgIdSettingsCostExportsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/credential-hygiene': {
      id: '/org/$orgId/settings/credential-hygiene'
      path: '/credential-hygiene'
      fullPath: '/org/$orgId/settings/credential-hygiene'
      preLoaderRoute: typeof OrgOrgIdSettingsCredentialHygieneRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/currency': {
      id: '/org/$orgId/settings/currency'
      path: '/currency'
      fullPath: '/org/$orgId/settings/currency'
      preLoaderRoute: typeof OrgOrgIdSettingsCurrencyRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/freezes': {
      id: '/org/$orgId/settings/freezes'
      path: '/freezes'
      fullPath: '/org/$orgId/settings/freezes'
      preLoaderRoute: typeof OrgOrgIdSettingsFreezesRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/jira': {
      id: '/org/$orgId/settings/jira'
      path: '/jira'
      fullPath: '/org/$orgId/settings/jira'
      preLoaderRoute: typeof OrgOrgIdSettingsJiraRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/linear': {
      id: '/org/$orgId/settings/linear'
      path: '/linear'
      fullPath: '/org/$orgId/settings/linear'
      preLoaderRoute: typeof OrgOrgIdSettingsLinearRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/paging': {
      id: '/org/$orgId/settings/paging'
      path: '/paging'
      fullPath: '/org/$orgId/settings/paging'
      preLoaderRoute: typeof OrgOrgIdSettingsPagingRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/roles': {
      id: '/org/$orgId/settings/roles'
      path: '/roles'
      fullPath: '/org/$orgId/settings/roles'
      preLoaderRoute: typeof OrgOrgIdSettingsRolesRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/session-recordings': {
      id: '/org/$orgId/settings/session-recordings'
      path: '/session-recordings'
      fullPath: '/org/$orgId/settings/session-recordings'
      preLoaderRoute: typeof OrgOrgIdSettingsSessionRecordingsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/ssh-host-keys': {
      id: '/org/$orgId/settings/ssh-host-keys'
      path: '/ssh-host-keys'
      fullPath: '/org/$orgId/settings/ssh-host-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsSshHostKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/ssh-keys': {
      id: '/org/$orgId/settings/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/org/$orgId/settings/ssh-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsSshKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/tag-policy': {
      id: '/org/$orgId/settings/tag-policy'
      path: '/tag-policy'
      fullPath: '/org/$orgId/settings/tag-policy'
      preLoaderRoute: typeof OrgOrgIdSettingsTagPolicyRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/team': {
      id: '/org/$orgId/settings/team'
      path: '/team'
      fullPath: '/org/$orgId/settings/team'
      preLoaderRoute: typeof OrgOrgIdSettingsTeamRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/workflows/$workflowId': {
      id: '/org/$orgId/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/org/$orgId/workflows/$workflowId'
      preLoaderRoute: typeof OrgOrgIdWorkflowsWorkflowIdRouteImport
      parentRoute: typeof OrgOrgIdWorkflowsRoute
    }
    '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': {
      id: '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
      path: '/resources/$pluginId/$resourceTypeId/$resourceId'
      fullPath: '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
      preLoaderRoute: typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
  }
}

interface OrgOrgIdChatRouteChildren {
  OrgOrgIdChatConversationIdRoute: typeof OrgOrgIdChatConversationIdRoute
  OrgOrgIdChatIndexRoute: typeof OrgOrgIdChatIndexRoute
}

const OrgOrgIdChatRouteChildren: OrgOrgIdChatRouteChildren = {
  OrgOrgIdChatConversationIdRoute: OrgOrgIdChatConversationIdRoute,
  OrgOrgIdChatIndexRoute: OrgOrgIdChatIndexRoute,
}

const OrgOrgIdChatRouteWithChildren = OrgOrgIdChatRoute._addFileChildren(
  OrgOrgIdChatRouteChildren,
)

interface OrgOrgIdCostReportsRouteChildren {
  OrgOrgIdCostReportsReportIdRoute: typeof OrgOrgIdCostReportsReportIdRoute
}

const OrgOrgIdCostReportsRouteChildren: OrgOrgIdCostReportsRouteChildren = {
  OrgOrgIdCostReportsReportIdRoute: OrgOrgIdCostReportsReportIdRoute,
}

const OrgOrgIdCostReportsRouteWithChildren =
  OrgOrgIdCostReportsRoute._addFileChildren(OrgOrgIdCostReportsRouteChildren)

interface OrgOrgIdIncidentsRouteChildren {
  OrgOrgIdIncidentsIncidentIdRoute: typeof OrgOrgIdIncidentsIncidentIdRoute
}

const OrgOrgIdIncidentsRouteChildren: OrgOrgIdIncidentsRouteChildren = {
  OrgOrgIdIncidentsIncidentIdRoute: OrgOrgIdIncidentsIncidentIdRoute,
}

const OrgOrgIdIncidentsRouteWithChildren =
  OrgOrgIdIncidentsRoute._addFileChildren(OrgOrgIdIncidentsRouteChildren)

interface OrgOrgIdInvoicesRouteChildren {
  OrgOrgIdInvoicesInvoiceIdRoute: typeof OrgOrgIdInvoicesInvoiceIdRoute
}

const OrgOrgIdInvoicesRouteChildren: OrgOrgIdInvoicesRouteChildren = {
  OrgOrgIdInvoicesInvoiceIdRoute: OrgOrgIdInvoicesInvoiceIdRoute,
}

const OrgOrgIdInvoicesRouteWithChildren =
  OrgOrgIdInvoicesRoute._addFileChildren(OrgOrgIdInvoicesRouteChildren)

interface OrgOrgIdSettingsRouteChildren {
  OrgOrgIdSettingsAccessRequestsRoute: typeof OrgOrgIdSettingsAccessRequestsRoute
  OrgOrgIdSettingsAgentsRoute: typeof OrgOrgIdSettingsAgentsRoute
  OrgOrgIdSettingsApiKeysRoute: typeof OrgOrgIdSettingsApiKeysRoute
  OrgOrgIdSettingsApprovalsRoute: typeof OrgOrgIdSettingsApprovalsRoute
  OrgOrgIdSettingsAuditLogRoute: typeof OrgOrgIdSettingsAuditLogRoute
  OrgOrgIdSettingsBastionsRoute: typeof OrgOrgIdSettingsBastionsRoute
  OrgOrgIdSettingsBillingRoute: typeof OrgOrgIdSettingsBillingRoute
  OrgOrgIdSettingsBillingRulesRoute: typeof OrgOrgIdSettingsBillingRulesRoute
  OrgOrgIdSettingsConfigRoute: typeof OrgOrgIdSettingsConfigRoute
  OrgOrgIdSettingsCostCentresRoute: typeof OrgOrgIdSettingsCostCentresRoute
  OrgOrgIdSettingsCostExportsRoute: typeof OrgOrgIdSettingsCostExportsRoute
  OrgOrgIdSettingsCredentialHygieneRoute: typeof OrgOrgIdSettingsCredentialHygieneRoute
  OrgOrgIdSettingsCurrencyRoute: typeof OrgOrgIdSettingsCurrencyRoute
  OrgOrgIdSettingsFreezesRoute: typeof OrgOrgIdSettingsFreezesRoute
  OrgOrgIdSettingsJiraRoute: typeof OrgOrgIdSettingsJiraRoute
  OrgOrgIdSettingsLinearRoute: typeof OrgOrgIdSettingsLinearRoute
  OrgOrgIdSettingsPagingRoute: typeof OrgOrgIdSettingsPagingRoute
  OrgOrgIdSettingsRolesRoute: typeof OrgOrgIdSettingsRolesRoute
  OrgOrgIdSettingsSessionRecordingsRoute: typeof OrgOrgIdSettingsSessionRecordingsRoute
  OrgOrgIdSettingsSshHostKeysRoute: typeof OrgOrgIdSettingsSshHostKeysRoute
  OrgOrgIdSettingsSshKeysRoute: typeof OrgOrgIdSettingsSshKeysRoute
  OrgOrgIdSettingsTagPolicyRoute: typeof OrgOrgIdSettingsTagPolicyRoute
  OrgOrgIdSettingsTeamRoute: typeof OrgOrgIdSettingsTeamRoute
  OrgOrgIdSettingsIndexRoute: typeof OrgOrgIdSettingsIndexRoute
}

const OrgOrgIdSettingsRouteChildren: OrgOrgIdSettingsRouteChildren = {
  OrgOrgIdSettingsAccessRequestsRoute: OrgOrgIdSettingsAccessRequestsRoute,
  OrgOrgIdSettingsAgentsRoute: OrgOrgIdSettingsAgentsRoute,
  OrgOrgIdSettingsApiKeysRoute: OrgOrgIdSettingsApiKeysRoute,
  OrgOrgIdSettingsApprovalsRoute: OrgOrgIdSettingsApprovalsRoute,
  OrgOrgIdSettingsAuditLogRoute: OrgOrgIdSettingsAuditLogRoute,
  OrgOrgIdSettingsBastionsRoute: OrgOrgIdSettingsBastionsRoute,
  OrgOrgIdSettingsBillingRoute: OrgOrgIdSettingsBillingRoute,
  OrgOrgIdSettingsBillingRulesRoute: OrgOrgIdSettingsBillingRulesRoute,
  OrgOrgIdSettingsConfigRoute: OrgOrgIdSettingsConfigRoute,
  OrgOrgIdSettingsCostCentresRoute: OrgOrgIdSettingsCostCentresRoute,
  OrgOrgIdSettingsCostExportsRoute: OrgOrgIdSettingsCostExportsRoute,
  OrgOrgIdSettingsCredentialHygieneRoute:
    OrgOrgIdSettingsCredentialHygieneRoute,
  OrgOrgIdSettingsCurrencyRoute: OrgOrgIdSettingsCurrencyRoute,
  OrgOrgIdSettingsFreezesRoute: OrgOrgIdSettingsFreezesRoute,
  OrgOrgIdSettingsJiraRoute: OrgOrgIdSettingsJiraRoute,
  OrgOrgIdSettingsLinearRoute: OrgOrgIdSettingsLinearRoute,
  OrgOrgIdSettingsPagingRoute: OrgOrgIdSettingsPagingRoute,
  OrgOrgIdSettingsRolesRoute: OrgOrgIdSettingsRolesRoute,
  OrgOrgIdSettingsSessionRecordingsRoute:
    OrgOrgIdSettingsSessionRecordingsRoute,
  OrgOrgIdSettingsSshHostKeysRoute: OrgOrgIdSettingsSshHostKeysRoute,
  OrgOrgIdSettingsSshKeysRoute: OrgOrgIdSettingsSshKeysRoute,
  OrgOrgIdSettingsTagPolicyRoute: OrgOrgIdSettingsTagPolicyRoute,
  OrgOrgIdSettingsTeamRoute: OrgOrgIdSettingsTeamRoute,
  OrgOrgIdSettingsIndexRoute: OrgOrgIdSettingsIndexRoute,
}

const OrgOrgIdSettingsRouteWithChildren =
  OrgOrgIdSettingsRoute._addFileChildren(OrgOrgIdSettingsRouteChildren)

interface OrgOrgIdWorkflowsRouteChildren {
  OrgOrgIdWorkflowsWorkflowIdRoute: typeof OrgOrgIdWorkflowsWorkflowIdRoute
}

const OrgOrgIdWorkflowsRouteChildren: OrgOrgIdWorkflowsRouteChildren = {
  OrgOrgIdWorkflowsWorkflowIdRoute: OrgOrgIdWorkflowsWorkflowIdRoute,
}

const OrgOrgIdWorkflowsRouteWithChildren =
  OrgOrgIdWorkflowsRoute._addFileChildren(OrgOrgIdWorkflowsRouteChildren)

interface OrgOrgIdRouteChildren {
  OrgOrgIdAccessReviewRoute: typeof OrgOrgIdAccessReviewRoute
  OrgOrgIdAgentsRoute: typeof OrgOrgIdAgentsRoute
  OrgOrgIdBackupsRoute: typeof OrgOrgIdBackupsRoute
  OrgOrgIdChangesRoute: typeof OrgOrgIdChangesRoute
  OrgOrgIdChatRoute: typeof OrgOrgIdChatRouteWithChildren
  OrgOrgIdCostReportsRoute: typeof OrgOrgIdCostReportsRouteWithChildren
  OrgOrgIdCostsRoute: typeof OrgOrgIdCostsRoute
  OrgOrgIdDeploymentsRoute: typeof OrgOrgIdDeploymentsRoute
  OrgOrgIdDnsRoute: typeof OrgOrgIdDnsRoute
  OrgOrgIdEnvironmentDiffRoute: typeof OrgOrgIdEnvironmentDiffRoute
  OrgOrgIdEnvironmentsRoute: typeof OrgOrgIdEnvironmentsRoute
  OrgOrgIdExpiringRoute: typeof OrgOrgIdExpiringRoute
  OrgOrgIdGraphRoute: typeof OrgOrgIdGraphRoute
  OrgOrgIdIacRoute: typeof OrgOrgIdIacRoute
  OrgOrgIdIncidentsRoute: typeof OrgOrgIdIncidentsRouteWithChildren
  OrgOrgIdInvoicesRoute: typeof OrgOrgIdInvoicesRouteWithChildren
  OrgOrgIdLogsRoute: typeof OrgOrgIdLogsRoute
  OrgOrgIdMetricAlertsRoute: typeof OrgOrgIdMetricAlertsRoute
  OrgOrgIdMomentRoute: typeof OrgOrgIdMomentRoute
  OrgOrgIdPostureRoute: typeof OrgOrgIdPostureRoute
  OrgOrgIdProbesRoute: typeof OrgOrgIdProbesRoute
  OrgOrgIdQuotasRoute: typeof OrgOrgIdQuotasRoute
  OrgOrgIdSavingsRoute: typeof OrgOrgIdSavingsRoute
  OrgOrgIdSettingsRoute: typeof OrgOrgIdSettingsRouteWithChildren
  OrgOrgIdSshFanoutRoute: typeof OrgOrgIdSshFanoutRoute
  OrgOrgIdStatusPagesRoute: typeof OrgOrgIdStatusPagesRoute
  OrgOrgIdWorkflowsRoute: typeof OrgOrgIdWorkflowsRouteWithChildren
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdAccountsAccountIdRoute: typeof OrgOrgIdAccountsAccountIdRoute
  OrgOrgIdDashboardDashboardIdRoute: typeof OrgOrgIdDashboardDashboardIdRoute
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute: typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdAccessReviewRoute: OrgOrgIdAccessReviewRoute,
  OrgOrgIdAgentsRoute: OrgOrgIdAgentsRoute,
  OrgOrgIdBackupsRoute: OrgOrgIdBackupsRoute,
  OrgOrgIdChangesRoute: OrgOrgIdChangesRoute,
  OrgOrgIdChatRoute: OrgOrgIdChatRouteWithChildren,
  OrgOrgIdCostReportsRoute: OrgOrgIdCostReportsRouteWithChildren,
  OrgOrgIdCostsRoute: OrgOrgIdCostsRoute,
  OrgOrgIdDeploymentsRoute: OrgOrgIdDeploymentsRoute,
  OrgOrgIdDnsRoute: OrgOrgIdDnsRoute,
  OrgOrgIdEnvironmentDiffRoute: OrgOrgIdEnvironmentDiffRoute,
  OrgOrgIdEnvironmentsRoute: OrgOrgIdEnvironmentsRoute,
  OrgOrgIdExpiringRoute: OrgOrgIdExpiringRoute,
  OrgOrgIdGraphRoute: OrgOrgIdGraphRoute,
  OrgOrgIdIacRoute: OrgOrgIdIacRoute,
  OrgOrgIdIncidentsRoute: OrgOrgIdIncidentsRouteWithChildren,
  OrgOrgIdInvoicesRoute: OrgOrgIdInvoicesRouteWithChildren,
  OrgOrgIdLogsRoute: OrgOrgIdLogsRoute,
  OrgOrgIdMetricAlertsRoute: OrgOrgIdMetricAlertsRoute,
  OrgOrgIdMomentRoute: OrgOrgIdMomentRoute,
  OrgOrgIdPostureRoute: OrgOrgIdPostureRoute,
  OrgOrgIdProbesRoute: OrgOrgIdProbesRoute,
  OrgOrgIdQuotasRoute: OrgOrgIdQuotasRoute,
  OrgOrgIdSavingsRoute: OrgOrgIdSavingsRoute,
  OrgOrgIdSettingsRoute: OrgOrgIdSettingsRouteWithChildren,
  OrgOrgIdSshFanoutRoute: OrgOrgIdSshFanoutRoute,
  OrgOrgIdStatusPagesRoute: OrgOrgIdStatusPagesRoute,
  OrgOrgIdWorkflowsRoute: OrgOrgIdWorkflowsRouteWithChildren,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdAccountsAccountIdRoute: OrgOrgIdAccountsAccountIdRoute,
  OrgOrgIdDashboardDashboardIdRoute: OrgOrgIdDashboardDashboardIdRoute,
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute:
    OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  ClaimRoute: ClaimRoute,
  OnboardingRoute: OnboardingRoute,
  DeploySplatRoute: DeploySplatRoute,
  InviteTokenRoute: InviteTokenRoute,
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
  StatusSlugRoute: StatusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
