/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DeploySplatRouteImport } from './routes/deploy.$'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OrgOrgIdRouteImport } from './routes/org.$orgId'
import { Route as StatusSlugRouteImport } from './routes/status.$slug'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org.$orgId.index'
import { Route as OrgOrgIdAgentsRouteImport } from './routes/org.$orgId.agents'
import { Route as OrgOrgIdChangesRouteImport } from './routes/org.$orgId.changes'
import { Route as OrgOrgIdChatRouteImport } from './routes/org.$orgId.chat'
import { Route as OrgOrgIdCostsRouteImport } from './routes/org.$orgId.costs'
import { Route as OrgOrgIdDeploymentsRouteImport } from './routes/org.$orgId.deployments'
import { Route as OrgOrgIdDnsRouteImport } from './routes/org.$orgId.dns'
import { Route as OrgOrgIdEnvironmentDiffRouteImport } from './routes/org.$orgId.environment-diff'
import { Route as OrgOrgIdExpiringRouteImport } from './routes/org.$orgId.expiring'
import { Route as OrgOrgIdGraphRouteImport } from './routes/org.$orgId.graph'
import { Route as OrgOrgIdLogsRouteImport } from './routes/org.$orgId.logs'
import { Route as OrgOrgIdMetricAlertsRouteImport } from './routes/org.$orgId.metric-alerts'
import { Route as OrgOrgIdMomentRouteImport } from './routes/org.$orgId.moment'
import { Route as OrgOrgIdPostureRouteImport } from './routes/org.$orgId.posture'
import { Route as OrgOrgIdProbesRouteImport } from './routes/org.$orgId.probes'
import { Route as OrgOrgIdSavingsRouteImport } from './routes/org.$orgId.savings'
import { Route as OrgOrgIdSettingsRouteImport } from './routes/org.$orgId.settings'
import { Route as OrgOrgIdSshFanoutRouteImport } from './routes/org.$orgId.ssh-fanout'
import { Route as OrgOrgIdWorkflowsRouteImport } from './routes/org.$orgId.workflows'
import { Route as OrgOrgIdAccountsAccountIdRouteImport } from './routes/org.$orgId.accounts.$accountId'
import { Route as OrgOrgIdChatIndexRouteImport } from './routes/org.$orgId.chat.index'
import { Route as OrgOrgIdChatConversationIdRouteImport } from './routes/org.$orgId.chat.$conversationId'
import { Route as OrgOrgIdDashboardDashboardIdRouteImport } from './routes/org.$orgId.dashboard.$dashboardId'
import { Route as OrgOrgIdSettingsIndexRouteImport } from './routes/org.$orgId.settings.index'
import { Route as OrgOrgIdSettingsAccessRequestsRouteImport } from './routes/org.$orgId.settings.access-requests'
import { Route as OrgOrgIdSettingsApiKeysRouteImport } from './routes/org.$orgId.settings.api-keys'
import { Route as OrgOrgIdSettingsApprovalsRouteImport } from './routes/org.$orgId.settings.approvals'
import { Route as OrgOrgIdSettingsAuditLogRouteImport } from './routes/org.$orgId.settings.audit-log'
import { Route as OrgOrgIdSettingsBastionsRouteImport } from './routes/org.$orgId.settings.bastions'
import { Route as OrgOrgIdSettingsBillingRouteImport } from './routes/org.$orgId.settings.billing'
import { Route as OrgOrgIdSettingsConfigRouteImport } from './routes/org.$orgId.settings.config'
import { Route as OrgOrgIdSettingsCredentialHygieneRouteImport } from './routes/org.$orgId.settings.credential-hygiene'
import { Route as OrgOrgIdSettingsFreezesRouteImport } from './routes/org.$orgId.settings.freezes'
import { Route as OrgOrgIdSettingsPagingRouteImport } from './routes/org.$orgId.settings.paging'
import { Route as OrgOrgIdSettingsRolesRouteImport } from './routes/org.$orgId.settings.roles'
import { Route as OrgOrgIdSettingsSessionRecordingsRouteImport } from './routes/org.$orgId.settings.session-recordings'
import { Route as OrgOrgIdSettingsSshHostKeysRouteImport } from './routes/org.$orgId.settings.ssh-host-keys'
import { Route as OrgOrgIdSettingsSshKeysRouteImport } from './routes/org.$orgId.settings.ssh-keys'
import { Route as OrgOrgIdSettingsTagPolicyRouteImport } from './routes/org.$orgId.settings.tag-policy'
import { Route as OrgOrgIdSettingsJiraRouteImport } from './routes/org.$orgId.settings.jira'
import { Route as OrgOrgIdSettingsTeamRouteImport } from './routes/org.$orgId.settings.team'
import { Route as OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport } from './routes/org.$orgId.resources.$pluginId.$resourceTypeId.$resourceId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploySplatRoute = DeploySplatRouteImport.update({
  id: '/deploy/$',
  path: '/deploy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdAgentsRoute = OrgOrgIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdChangesRoute = OrgOrgIdChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdChatRoute = OrgOrgIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdCostsRoute = OrgOrgIdCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdDeploymentsRoute = OrgOrgIdDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdDnsRoute = OrgOrgIdDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdEnvironmentDiffRoute = OrgOrgIdEnvironmentDiffRouteImport.update({
  id: '/environment-diff',
  path: '/environment-diff',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdExpiringRoute = OrgOrgIdExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdGraphRoute = OrgOrgIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdLogsRoute = OrgOrgIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdMetricAlertsRoute = OrgOrgIdMetricAlertsRouteImport.update({
  id: '/metric-alerts',
  path: '/metric-alerts',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdMomentRoute = OrgOrgIdMomentRouteImport.update({
  id: '/moment',
  path: '/moment',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdPostureRoute = OrgOrgIdPostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdProbesRoute = OrgOrgIdProbesRouteImport.update({
  id: '/probes',
  path: '/probes',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSavingsRoute = OrgOrgIdSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsRoute = OrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSshFanoutRoute = OrgOrgIdSshFanoutRouteImport.update({
  id: '/ssh-fanout',
  path: '/ssh-fanout',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdWorkflowsRoute = OrgOrgIdWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdAccountsAccountIdRoute =
  OrgOrgIdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdChatIndexRoute = OrgOrgIdChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdChatRoute,
} as any)
const OrgOrgIdChatConversationIdRoute =
  OrgOrgIdChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => OrgOrgIdChatRoute,
  } as any)
const OrgOrgIdDashboardDashboardIdRoute =
  OrgOrgIdDashboardDashboardIdRouteImport.update({
    id: '/dashboard/$dashboardId',
    path: '/dashboard/$dashboardId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdSettingsIndexRoute = OrgOrgIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsAccessRequestsRoute =
  OrgOrgIdSettingsAccessRequestsRouteImport.update({
    id: '/access-requests',
    path: '/access-requests',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsApiKeysRoute = OrgOrgIdSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsApprovalsRoute =
  OrgOrgIdSettingsApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsAuditLogRoute =
  OrgOrgIdSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsBastionsRoute =
  OrgOrgIdSettingsBastionsRouteImport.update({
    id: '/bastions',
    path: '/bastions',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsBillingRoute = OrgOrgIdSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsConfigRoute = OrgOrgIdSettingsConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsCredentialHygieneRoute =
  OrgOrgIdSettingsCredentialHygieneRouteImport.update({
    id: '/credential-hygiene',
    path: '/credential-hygiene',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsFreezesRoute = OrgOrgIdSettingsFreezesRouteImport.update({
  id: '/freezes',
  path: '/freezes',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsPagingRoute = OrgOrgIdSettingsPagingRouteImport.update({
  id: '/paging',
  path: '/paging',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsRolesRoute = OrgOrgIdSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsSessionRecordingsRoute =
  OrgOrgIdSettingsSessionRecordingsRouteImport.update({
    id: '/session-recordings',
    path: '/session-recordings',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsSshHostKeysRoute =
  OrgOrgIdSettingsSshHostKeysRouteImport.update({
    id: '/ssh-host-keys',
    path: '/ssh-host-keys',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsSshKeysRoute = OrgOrgIdSettingsSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsTagPolicyRoute =
  OrgOrgIdSettingsTagPolicyRouteImport.update({
    id: '/tag-policy',
    path: '/tag-policy',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)

const OrgOrgIdSettingsJiraRoute =
  OrgOrgIdSettingsJiraRouteImport.update({
    id: '/jira',
    path: '/jira',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsTeamRoute = OrgOrgIdSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute =
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport.update({
    id: '/resources/$pluginId/$resourceTypeId/$resourceId',
    path: '/resources/$pluginId/$resourceTypeId/$resourceId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/deploy/$': typeof DeploySplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/org/$orgId/agents': typeof OrgOrgIdAgentsRoute
  '/org/$orgId/changes': typeof OrgOrgIdChangesRoute
  '/org/$orgId/chat': typeof OrgOrgIdChatRouteWithChildren
  '/org/$orgId/costs': typeof OrgOrgIdCostsRoute
  '/org/$orgId/deployments': typeof OrgOrgIdDeploymentsRoute
  '/org/$orgId/dns': typeof OrgOrgIdDnsRoute
  '/org/$orgId/environment-diff': typeof OrgOrgIdEnvironmentDiffRoute
  '/org/$orgId/expiring': typeof OrgOrgIdExpiringRoute
  '/org/$orgId/graph': typeof OrgOrgIdGraphRoute
  '/org/$orgId/logs': typeof OrgOrgIdLogsRoute
  '/org/$orgId/metric-alerts': typeof OrgOrgIdMetricAlertsRoute
  '/org/$orgId/moment': typeof OrgOrgIdMomentRoute
  '/org/$orgId/posture': typeof OrgOrgIdPostureRoute
  '/org/$orgId/probes': typeof OrgOrgIdProbesRoute
  '/org/$orgId/savings': typeof OrgOrgIdSavingsRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/ssh-fanout': typeof OrgOrgIdSshFanoutRoute
  '/org/$orgId/workflows': typeof OrgOrgIdWorkflowsRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/chat/$conversationId': typeof OrgOrgIdChatConversationIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/settings/access-requests': typeof OrgOrgIdSettingsAccessRequestsRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/approvals': typeof OrgOrgIdSettingsApprovalsRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/bastions': typeof OrgOrgIdSettingsBastionsRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/config': typeof OrgOrgIdSettingsConfigRoute
  '/org/$orgId/settings/credential-hygiene': typeof OrgOrgIdSettingsCredentialHygieneRoute
  '/org/$orgId/settings/freezes': typeof OrgOrgIdSettingsFreezesRoute
  '/org/$orgId/settings/paging': typeof OrgOrgIdSettingsPagingRoute
  '/org/$orgId/settings/roles': typeof OrgOrgIdSettingsRolesRoute
  '/org/$orgId/settings/session-recordings': typeof OrgOrgIdSettingsSessionRecordingsRoute
  '/org/$orgId/settings/ssh-host-keys': typeof OrgOrgIdSettingsSshHostKeysRoute
  '/org/$orgId/settings/ssh-keys': typeof OrgOrgIdSettingsSshKeysRoute
  '/org/$orgId/settings/tag-policy': typeof OrgOrgIdSettingsTagPolicyRoute
  '/org/$orgId/settings/jira': typeof OrgOrgIdSettingsJiraRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/chat/': typeof OrgOrgIdChatIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/deploy/$': typeof DeploySplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/org/$orgId/agents': typeof OrgOrgIdAgentsRoute
  '/org/$orgId/changes': typeof OrgOrgIdChangesRoute
  '/org/$orgId/costs': typeof OrgOrgIdCostsRoute
  '/org/$orgId/deployments': typeof OrgOrgIdDeploymentsRoute
  '/org/$orgId/dns': typeof OrgOrgIdDnsRoute
  '/org/$orgId/environment-diff': typeof OrgOrgIdEnvironmentDiffRoute
  '/org/$orgId/expiring': typeof OrgOrgIdExpiringRoute
  '/org/$orgId/graph': typeof OrgOrgIdGraphRoute
  '/org/$orgId/logs': typeof OrgOrgIdLogsRoute
  '/org/$orgId/metric-alerts': typeof OrgOrgIdMetricAlertsRoute
  '/org/$orgId/moment': typeof OrgOrgIdMomentRoute
  '/org/$orgId/posture': typeof OrgOrgIdPostureRoute
  '/org/$orgId/probes': typeof OrgOrgIdProbesRoute
  '/org/$orgId/savings': typeof OrgOrgIdSavingsRoute
  '/org/$orgId/ssh-fanout': typeof OrgOrgIdSshFanoutRoute
  '/org/$orgId/workflows': typeof OrgOrgIdWorkflowsRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/chat/$conversationId': typeof OrgOrgIdChatConversationIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/settings/access-requests': typeof OrgOrgIdSettingsAccessRequestsRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/approvals': typeof OrgOrgIdSettingsApprovalsRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/bastions': typeof OrgOrgIdSettingsBastionsRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/config': typeof OrgOrgIdSettingsConfigRoute
  '/org/$orgId/settings/credential-hygiene': typeof OrgOrgIdSettingsCredentialHygieneRoute
  '/org/$orgId/settings/freezes': typeof OrgOrgIdSettingsFreezesRoute
  '/org/$orgId/settings/paging': typeof OrgOrgIdSettingsPagingRoute
  '/org/$orgId/settings/roles': typeof OrgOrgIdSettingsRolesRoute
  '/org/$orgId/settings/session-recordings': typeof OrgOrgIdSettingsSessionRecordingsRoute
  '/org/$orgId/settings/ssh-host-keys': typeof OrgOrgIdSettingsSshHostKeysRoute
  '/org/$orgId/settings/ssh-keys': typeof OrgOrgIdSettingsSshKeysRoute
  '/org/$orgId/settings/tag-policy': typeof OrgOrgIdSettingsTagPolicyRoute
  '/org/$orgId/settings/jira': typeof OrgOrgIdSettingsJiraRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/chat': typeof OrgOrgIdChatIndexRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/deploy/$': typeof DeploySplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/status/$slug': typeof StatusSlugRoute
  '/org/$orgId/agents': typeof OrgOrgIdAgentsRoute
  '/org/$orgId/changes': typeof OrgOrgIdChangesRoute
  '/org/$orgId/chat': typeof OrgOrgIdChatRouteWithChildren
  '/org/$orgId/costs': typeof OrgOrgIdCostsRoute
  '/org/$orgId/deployments': typeof OrgOrgIdDeploymentsRoute
  '/org/$orgId/dns': typeof OrgOrgIdDnsRoute
  '/org/$orgId/environment-diff': typeof OrgOrgIdEnvironmentDiffRoute
  '/org/$orgId/expiring': typeof OrgOrgIdExpiringRoute
  '/org/$orgId/graph': typeof OrgOrgIdGraphRoute
  '/org/$orgId/logs': typeof OrgOrgIdLogsRoute
  '/org/$orgId/metric-alerts': typeof OrgOrgIdMetricAlertsRoute
  '/org/$orgId/moment': typeof OrgOrgIdMomentRoute
  '/org/$orgId/posture': typeof OrgOrgIdPostureRoute
  '/org/$orgId/probes': typeof OrgOrgIdProbesRoute
  '/org/$orgId/savings': typeof OrgOrgIdSavingsRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/ssh-fanout': typeof OrgOrgIdSshFanoutRoute
  '/org/$orgId/workflows': typeof OrgOrgIdWorkflowsRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/chat/$conversationId': typeof OrgOrgIdChatConversationIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/settings/access-requests': typeof OrgOrgIdSettingsAccessRequestsRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/approvals': typeof OrgOrgIdSettingsApprovalsRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/bastions': typeof OrgOrgIdSettingsBastionsRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/config': typeof OrgOrgIdSettingsConfigRoute
  '/org/$orgId/settings/credential-hygiene': typeof OrgOrgIdSettingsCredentialHygieneRoute
  '/org/$orgId/settings/freezes': typeof OrgOrgIdSettingsFreezesRoute
  '/org/$orgId/settings/paging': typeof OrgOrgIdSettingsPagingRoute
  '/org/$orgId/settings/roles': typeof OrgOrgIdSettingsRolesRoute
  '/org/$orgId/settings/session-recordings': typeof OrgOrgIdSettingsSessionRecordingsRoute
  '/org/$orgId/settings/ssh-host-keys': typeof OrgOrgIdSettingsSshHostKeysRoute
  '/org/$orgId/settings/ssh-keys': typeof OrgOrgIdSettingsSshKeysRoute
  '/org/$orgId/settings/tag-policy': typeof OrgOrgIdSettingsTagPolicyRoute
  '/org/$orgId/settings/jira': typeof OrgOrgIdSettingsJiraRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/chat/': typeof OrgOrgIdChatIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/onboarding'
    | '/deploy/$'
    | '/invite/$token'
    | '/org/$orgId'
    | '/status/$slug'
    | '/org/$orgId/agents'
    | '/org/$orgId/changes'
    | '/org/$orgId/chat'
    | '/org/$orgId/costs'
    | '/org/$orgId/deployments'
    | '/org/$orgId/dns'
    | '/org/$orgId/environment-diff'
    | '/org/$orgId/expiring'
    | '/org/$orgId/graph'
    | '/org/$orgId/logs'
    | '/org/$orgId/metric-alerts'
    | '/org/$orgId/moment'
    | '/org/$orgId/posture'
    | '/org/$orgId/probes'
    | '/org/$orgId/savings'
    | '/org/$orgId/settings'
    | '/org/$orgId/ssh-fanout'
    | '/org/$orgId/workflows'
    | '/org/$orgId/'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/chat/$conversationId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/settings/access-requests'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/approvals'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/bastions'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/config'
    | '/org/$orgId/settings/credential-hygiene'
    | '/org/$orgId/settings/freezes'
    | '/org/$orgId/settings/paging'
    | '/org/$orgId/settings/roles'
    | '/org/$orgId/settings/session-recordings'
    | '/org/$orgId/settings/ssh-host-keys'
    | '/org/$orgId/settings/ssh-keys'
    | '/org/$orgId/settings/tag-policy'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/chat/'
    | '/org/$orgId/settings/'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/onboarding'
    | '/deploy/$'
    | '/invite/$token'
    | '/status/$slug'
    | '/org/$orgId/agents'
    | '/org/$orgId/changes'
    | '/org/$orgId/costs'
    | '/org/$orgId/deployments'
    | '/org/$orgId/dns'
    | '/org/$orgId/environment-diff'
    | '/org/$orgId/expiring'
    | '/org/$orgId/graph'
    | '/org/$orgId/logs'
    | '/org/$orgId/metric-alerts'
    | '/org/$orgId/moment'
    | '/org/$orgId/posture'
    | '/org/$orgId/probes'
    | '/org/$orgId/savings'
    | '/org/$orgId/ssh-fanout'
    | '/org/$orgId/workflows'
    | '/org/$orgId'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/chat/$conversationId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/settings/access-requests'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/approvals'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/bastions'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/config'
    | '/org/$orgId/settings/credential-hygiene'
    | '/org/$orgId/settings/freezes'
    | '/org/$orgId/settings/paging'
    | '/org/$orgId/settings/roles'
    | '/org/$orgId/settings/session-recordings'
    | '/org/$orgId/settings/ssh-host-keys'
    | '/org/$orgId/settings/ssh-keys'
    | '/org/$orgId/settings/tag-policy'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/chat'
    | '/org/$orgId/settings'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  id:
    | '__root__'
    | '/admin'
    | '/onboarding'
    | '/deploy/$'
    | '/invite/$token'
    | '/org/$orgId'
    | '/status/$slug'
    | '/org/$orgId/agents'
    | '/org/$orgId/changes'
    | '/org/$orgId/chat'
    | '/org/$orgId/costs'
    | '/org/$orgId/deployments'
    | '/org/$orgId/dns'
    | '/org/$orgId/environment-diff'
    | '/org/$orgId/expiring'
    | '/org/$orgId/graph'
    | '/org/$orgId/logs'
    | '/org/$orgId/metric-alerts'
    | '/org/$orgId/moment'
    | '/org/$orgId/posture'
    | '/org/$orgId/probes'
    | '/org/$orgId/savings'
    | '/org/$orgId/settings'
    | '/org/$orgId/ssh-fanout'
    | '/org/$orgId/workflows'
    | '/org/$orgId/'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/chat/$conversationId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/settings/access-requests'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/approvals'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/bastions'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/config'
    | '/org/$orgId/settings/credential-hygiene'
    | '/org/$orgId/settings/freezes'
    | '/org/$orgId/settings/paging'
    | '/org/$orgId/settings/roles'
    | '/org/$orgId/settings/session-recordings'
    | '/org/$orgId/settings/ssh-host-keys'
    | '/org/$orgId/settings/ssh-keys'
    | '/org/$orgId/settings/tag-policy'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/chat/'
    | '/org/$orgId/settings/'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  OnboardingRoute: typeof OnboardingRoute
  DeploySplatRoute: typeof DeploySplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
  StatusSlugRoute: typeof StatusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy/$': {
      id: '/deploy/$'
      path: '/deploy/$'
      fullPath: '/deploy/$'
      preLoaderRoute: typeof DeploySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/agents': {
      id: '/org/$orgId/agents'
      path: '/agents'
      fullPath: '/org/$orgId/agents'
      preLoaderRoute: typeof OrgOrgIdAgentsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/changes': {
      id: '/org/$orgId/changes'
      path: '/changes'
      fullPath: '/org/$orgId/changes'
      preLoaderRoute: typeof OrgOrgIdChangesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/chat': {
      id: '/org/$orgId/chat'
      path: '/chat'
      fullPath: '/org/$orgId/chat'
      preLoaderRoute: typeof OrgOrgIdChatRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/costs': {
      id: '/org/$orgId/costs'
      path: '/costs'
      fullPath: '/org/$orgId/costs'
      preLoaderRoute: typeof OrgOrgIdCostsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/deployments': {
      id: '/org/$orgId/deployments'
      path: '/deployments'
      fullPath: '/org/$orgId/deployments'
      preLoaderRoute: typeof OrgOrgIdDeploymentsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/dns': {
      id: '/org/$orgId/dns'
      path: '/dns'
      fullPath: '/org/$orgId/dns'
      preLoaderRoute: typeof OrgOrgIdDnsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/environment-diff': {
      id: '/org/$orgId/environment-diff'
      path: '/environment-diff'
      fullPath: '/org/$orgId/environment-diff'
      preLoaderRoute: typeof OrgOrgIdEnvironmentDiffRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/expiring': {
      id: '/org/$orgId/expiring'
      path: '/expiring'
      fullPath: '/org/$orgId/expiring'
      preLoaderRoute: typeof OrgOrgIdExpiringRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/graph': {
      id: '/org/$orgId/graph'
      path: '/graph'
      fullPath: '/org/$orgId/graph'
      preLoaderRoute: typeof OrgOrgIdGraphRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/logs': {
      id: '/org/$orgId/logs'
      path: '/logs'
      fullPath: '/org/$orgId/logs'
      preLoaderRoute: typeof OrgOrgIdLogsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/metric-alerts': {
      id: '/org/$orgId/metric-alerts'
      path: '/metric-alerts'
      fullPath: '/org/$orgId/metric-alerts'
      preLoaderRoute: typeof OrgOrgIdMetricAlertsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/moment': {
      id: '/org/$orgId/moment'
      path: '/moment'
      fullPath: '/org/$orgId/moment'
      preLoaderRoute: typeof OrgOrgIdMomentRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/posture': {
      id: '/org/$orgId/posture'
      path: '/posture'
      fullPath: '/org/$orgId/posture'
      preLoaderRoute: typeof OrgOrgIdPostureRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/probes': {
      id: '/org/$orgId/probes'
      path: '/probes'
      fullPath: '/org/$orgId/probes'
      preLoaderRoute: typeof OrgOrgIdProbesRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/savings': {
      id: '/org/$orgId/savings'
      path: '/savings'
      fullPath: '/org/$orgId/savings'
      preLoaderRoute: typeof OrgOrgIdSavingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings': {
      id: '/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof OrgOrgIdSettingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/ssh-fanout': {
      id: '/org/$orgId/ssh-fanout'
      path: '/ssh-fanout'
      fullPath: '/org/$orgId/ssh-fanout'
      preLoaderRoute: typeof OrgOrgIdSshFanoutRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/workflows': {
      id: '/org/$orgId/workflows'
      path: '/workflows'
      fullPath: '/org/$orgId/workflows'
      preLoaderRoute: typeof OrgOrgIdWorkflowsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/accounts/$accountId': {
      id: '/org/$orgId/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/org/$orgId/accounts/$accountId'
      preLoaderRoute: typeof OrgOrgIdAccountsAccountIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/chat/': {
      id: '/org/$orgId/chat/'
      path: '/'
      fullPath: '/org/$orgId/chat/'
      preLoaderRoute: typeof OrgOrgIdChatIndexRouteImport
      parentRoute: typeof OrgOrgIdChatRoute
    }
    '/org/$orgId/chat/$conversationId': {
      id: '/org/$orgId/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/org/$orgId/chat/$conversationId'
      preLoaderRoute: typeof OrgOrgIdChatConversationIdRouteImport
      parentRoute: typeof OrgOrgIdChatRoute
    }
    '/org/$orgId/dashboard/$dashboardId': {
      id: '/org/$orgId/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/org/$orgId/dashboard/$dashboardId'
      preLoaderRoute: typeof OrgOrgIdDashboardDashboardIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings/': {
      id: '/org/$orgId/settings/'
      path: '/'
      fullPath: '/org/$orgId/settings/'
      preLoaderRoute: typeof OrgOrgIdSettingsIndexRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/access-requests': {
      id: '/org/$orgId/settings/access-requests'
      path: '/access-requests'
      fullPath: '/org/$orgId/settings/access-requests'
      preLoaderRoute: typeof OrgOrgIdSettingsAccessRequestsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/jira': {
      id: '/org/$orgId/settings/jira'
      path: '/jira'
      fullPath: '/org/$orgId/settings/jira'
      preLoaderRoute: typeof OrgOrgIdSettingsJiraRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/api-keys': {
      id: '/org/$orgId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/org/$orgId/settings/api-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsApiKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/approvals': {
      id: '/org/$orgId/settings/approvals'
      path: '/approvals'
      fullPath: '/org/$orgId/settings/approvals'
      preLoaderRoute: typeof OrgOrgIdSettingsApprovalsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/audit-log': {
      id: '/org/$orgId/settings/audit-log'
      path: '/audit-log'
      fullPath: '/org/$orgId/settings/audit-log'
      preLoaderRoute: typeof OrgOrgIdSettingsAuditLogRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/bastions': {
      id: '/org/$orgId/settings/bastions'
      path: '/bastions'
      fullPath: '/org/$orgId/settings/bastions'
      preLoaderRoute: typeof OrgOrgIdSettingsBastionsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/billing': {
      id: '/org/$orgId/settings/billing'
      path: '/billing'
      fullPath: '/org/$orgId/settings/billing'
      preLoaderRoute: typeof OrgOrgIdSettingsBillingRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/config': {
      id: '/org/$orgId/settings/config'
      path: '/config'
      fullPath: '/org/$orgId/settings/config'
      preLoaderRoute: typeof OrgOrgIdSettingsConfigRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/credential-hygiene': {
      id: '/org/$orgId/settings/credential-hygiene'
      path: '/credential-hygiene'
      fullPath: '/org/$orgId/settings/credential-hygiene'
      preLoaderRoute: typeof OrgOrgIdSettingsCredentialHygieneRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/freezes': {
      id: '/org/$orgId/settings/freezes'
      path: '/freezes'
      fullPath: '/org/$orgId/settings/freezes'
      preLoaderRoute: typeof OrgOrgIdSettingsFreezesRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/paging': {
      id: '/org/$orgId/settings/paging'
      path: '/paging'
      fullPath: '/org/$orgId/settings/paging'
      preLoaderRoute: typeof OrgOrgIdSettingsPagingRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/roles': {
      id: '/org/$orgId/settings/roles'
      path: '/roles'
      fullPath: '/org/$orgId/settings/roles'
      preLoaderRoute: typeof OrgOrgIdSettingsRolesRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/session-recordings': {
      id: '/org/$orgId/settings/session-recordings'
      path: '/session-recordings'
      fullPath: '/org/$orgId/settings/session-recordings'
      preLoaderRoute: typeof OrgOrgIdSettingsSessionRecordingsRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/ssh-host-keys': {
      id: '/org/$orgId/settings/ssh-host-keys'
      path: '/ssh-host-keys'
      fullPath: '/org/$orgId/settings/ssh-host-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsSshHostKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/ssh-keys': {
      id: '/org/$orgId/settings/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/org/$orgId/settings/ssh-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsSshKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/tag-policy': {
      id: '/org/$orgId/settings/tag-policy'
      path: '/tag-policy'
      fullPath: '/org/$orgId/settings/tag-policy'
      preLoaderRoute: typeof OrgOrgIdSettingsTagPolicyRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/team': {
      id: '/org/$orgId/settings/team'
      path: '/team'
      fullPath: '/org/$orgId/settings/team'
      preLoaderRoute: typeof OrgOrgIdSettingsTeamRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': {
      id: '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
      path: '/resources/$pluginId/$resourceTypeId/$resourceId'
      fullPath: '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
      preLoaderRoute: typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
  }
}

interface OrgOrgIdChatRouteChildren {
  OrgOrgIdChatConversationIdRoute: typeof OrgOrgIdChatConversationIdRoute
  OrgOrgIdChatIndexRoute: typeof OrgOrgIdChatIndexRoute
}

const OrgOrgIdChatRouteChildren: OrgOrgIdChatRouteChildren = {
  OrgOrgIdChatConversationIdRoute: OrgOrgIdChatConversationIdRoute,
  OrgOrgIdChatIndexRoute: OrgOrgIdChatIndexRoute,
}

const OrgOrgIdChatRouteWithChildren = OrgOrgIdChatRoute._addFileChildren(
  OrgOrgIdChatRouteChildren,
)

interface OrgOrgIdSettingsRouteChildren {
  OrgOrgIdSettingsAccessRequestsRoute: typeof OrgOrgIdSettingsAccessRequestsRoute
  OrgOrgIdSettingsApiKeysRoute: typeof OrgOrgIdSettingsApiKeysRoute
  OrgOrgIdSettingsApprovalsRoute: typeof OrgOrgIdSettingsApprovalsRoute
  OrgOrgIdSettingsAuditLogRoute: typeof OrgOrgIdSettingsAuditLogRoute
  OrgOrgIdSettingsBastionsRoute: typeof OrgOrgIdSettingsBastionsRoute
  OrgOrgIdSettingsBillingRoute: typeof OrgOrgIdSettingsBillingRoute
  OrgOrgIdSettingsConfigRoute: typeof OrgOrgIdSettingsConfigRoute
  OrgOrgIdSettingsCredentialHygieneRoute: typeof OrgOrgIdSettingsCredentialHygieneRoute
  OrgOrgIdSettingsFreezesRoute: typeof OrgOrgIdSettingsFreezesRoute
  OrgOrgIdSettingsPagingRoute: typeof OrgOrgIdSettingsPagingRoute
  OrgOrgIdSettingsRolesRoute: typeof OrgOrgIdSettingsRolesRoute
  OrgOrgIdSettingsSessionRecordingsRoute: typeof OrgOrgIdSettingsSessionRecordingsRoute
  OrgOrgIdSettingsSshHostKeysRoute: typeof OrgOrgIdSettingsSshHostKeysRoute
  OrgOrgIdSettingsSshKeysRoute: typeof OrgOrgIdSettingsSshKeysRoute
  OrgOrgIdSettingsTagPolicyRoute: typeof OrgOrgIdSettingsTagPolicyRoute
  OrgOrgIdSettingsJiraRoute: typeof OrgOrgIdSettingsJiraRoute
  OrgOrgIdSettingsTeamRoute: typeof OrgOrgIdSettingsTeamRoute
  OrgOrgIdSettingsIndexRoute: typeof OrgOrgIdSettingsIndexRoute
}

const OrgOrgIdSettingsRouteChildren: OrgOrgIdSettingsRouteChildren = {
  OrgOrgIdSettingsAccessRequestsRoute: OrgOrgIdSettingsAccessRequestsRoute,
  OrgOrgIdSettingsApiKeysRoute: OrgOrgIdSettingsApiKeysRoute,
  OrgOrgIdSettingsApprovalsRoute: OrgOrgIdSettingsApprovalsRoute,
  OrgOrgIdSettingsAuditLogRoute: OrgOrgIdSettingsAuditLogRoute,
  OrgOrgIdSettingsBastionsRoute: OrgOrgIdSettingsBastionsRoute,
  OrgOrgIdSettingsBillingRoute: OrgOrgIdSettingsBillingRoute,
  OrgOrgIdSettingsConfigRoute: OrgOrgIdSettingsConfigRoute,
  OrgOrgIdSettingsCredentialHygieneRoute:
    OrgOrgIdSettingsCredentialHygieneRoute,
  OrgOrgIdSettingsFreezesRoute: OrgOrgIdSettingsFreezesRoute,
  OrgOrgIdSettingsPagingRoute: OrgOrgIdSettingsPagingRoute,
  OrgOrgIdSettingsRolesRoute: OrgOrgIdSettingsRolesRoute,
  OrgOrgIdSettingsSessionRecordingsRoute:
    OrgOrgIdSettingsSessionRecordingsRoute,
  OrgOrgIdSettingsSshHostKeysRoute: OrgOrgIdSettingsSshHostKeysRoute,
  OrgOrgIdSettingsSshKeysRoute: OrgOrgIdSettingsSshKeysRoute,
  OrgOrgIdSettingsTagPolicyRoute: OrgOrgIdSettingsTagPolicyRoute,
  OrgOrgIdSettingsJiraRoute: OrgOrgIdSettingsJiraRoute,
  OrgOrgIdSettingsTeamRoute: OrgOrgIdSettingsTeamRoute,
  OrgOrgIdSettingsIndexRoute: OrgOrgIdSettingsIndexRoute,
}

const OrgOrgIdSettingsRouteWithChildren =
  OrgOrgIdSettingsRoute._addFileChildren(OrgOrgIdSettingsRouteChildren)

interface OrgOrgIdRouteChildren {
  OrgOrgIdAgentsRoute: typeof OrgOrgIdAgentsRoute
  OrgOrgIdChangesRoute: typeof OrgOrgIdChangesRoute
  OrgOrgIdChatRoute: typeof OrgOrgIdChatRouteWithChildren
  OrgOrgIdCostsRoute: typeof OrgOrgIdCostsRoute
  OrgOrgIdDeploymentsRoute: typeof OrgOrgIdDeploymentsRoute
  OrgOrgIdDnsRoute: typeof OrgOrgIdDnsRoute
  OrgOrgIdEnvironmentDiffRoute: typeof OrgOrgIdEnvironmentDiffRoute
  OrgOrgIdExpiringRoute: typeof OrgOrgIdExpiringRoute
  OrgOrgIdGraphRoute: typeof OrgOrgIdGraphRoute
  OrgOrgIdLogsRoute: typeof OrgOrgIdLogsRoute
  OrgOrgIdMetricAlertsRoute: typeof OrgOrgIdMetricAlertsRoute
  OrgOrgIdMomentRoute: typeof OrgOrgIdMomentRoute
  OrgOrgIdPostureRoute: typeof OrgOrgIdPostureRoute
  OrgOrgIdProbesRoute: typeof OrgOrgIdProbesRoute
  OrgOrgIdSavingsRoute: typeof OrgOrgIdSavingsRoute
  OrgOrgIdSettingsRoute: typeof OrgOrgIdSettingsRouteWithChildren
  OrgOrgIdSshFanoutRoute: typeof OrgOrgIdSshFanoutRoute
  OrgOrgIdWorkflowsRoute: typeof OrgOrgIdWorkflowsRoute
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdAccountsAccountIdRoute: typeof OrgOrgIdAccountsAccountIdRoute
  OrgOrgIdDashboardDashboardIdRoute: typeof OrgOrgIdDashboardDashboardIdRoute
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute: typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdAgentsRoute: OrgOrgIdAgentsRoute,
  OrgOrgIdChangesRoute: OrgOrgIdChangesRoute,
  OrgOrgIdChatRoute: OrgOrgIdChatRouteWithChildren,
  OrgOrgIdCostsRoute: OrgOrgIdCostsRoute,
  OrgOrgIdDeploymentsRoute: OrgOrgIdDeploymentsRoute,
  OrgOrgIdDnsRoute: OrgOrgIdDnsRoute,
  OrgOrgIdEnvironmentDiffRoute: OrgOrgIdEnvironmentDiffRoute,
  OrgOrgIdExpiringRoute: OrgOrgIdExpiringRoute,
  OrgOrgIdGraphRoute: OrgOrgIdGraphRoute,
  OrgOrgIdLogsRoute: OrgOrgIdLogsRoute,
  OrgOrgIdMetricAlertsRoute: OrgOrgIdMetricAlertsRoute,
  OrgOrgIdMomentRoute: OrgOrgIdMomentRoute,
  OrgOrgIdPostureRoute: OrgOrgIdPostureRoute,
  OrgOrgIdProbesRoute: OrgOrgIdProbesRoute,
  OrgOrgIdSavingsRoute: OrgOrgIdSavingsRoute,
  OrgOrgIdSettingsRoute: OrgOrgIdSettingsRouteWithChildren,
  OrgOrgIdSshFanoutRoute: OrgOrgIdSshFanoutRoute,
  OrgOrgIdWorkflowsRoute: OrgOrgIdWorkflowsRoute,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdAccountsAccountIdRoute: OrgOrgIdAccountsAccountIdRoute,
  OrgOrgIdDashboardDashboardIdRoute: OrgOrgIdDashboardDashboardIdRoute,
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute:
    OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  OnboardingRoute: OnboardingRoute,
  DeploySplatRoute: DeploySplatRoute,
  InviteTokenRoute: InviteTokenRoute,
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
  StatusSlugRoute: StatusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
