/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrgOrgIdRouteImport } from './routes/org.$orgId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org.$orgId.index'
import { Route as OrgOrgIdSettingsRouteImport } from './routes/org.$orgId.settings'
import { Route as OrgOrgIdSettingsIndexRouteImport } from './routes/org.$orgId.settings.index'
import { Route as OrgOrgIdSettingsTeamRouteImport } from './routes/org.$orgId.settings.team'
import { Route as OrgOrgIdSettingsBillingRouteImport } from './routes/org.$orgId.settings.billing'
import { Route as OrgOrgIdSettingsAuditLogRouteImport } from './routes/org.$orgId.settings.audit-log'
import { Route as OrgOrgIdSettingsApiKeysRouteImport } from './routes/org.$orgId.settings.api-keys'
import { Route as OrgOrgIdDashboardDashboardIdRouteImport } from './routes/org.$orgId.dashboard.$dashboardId'
import { Route as OrgOrgIdAccountsAccountIdRouteImport } from './routes/org.$orgId.accounts.$accountId'
import { Route as OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport } from './routes/org.$orgId.resources.$pluginId.$resourceTypeId.$resourceId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsRoute = OrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsIndexRoute = OrgOrgIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsTeamRoute = OrgOrgIdSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsBillingRoute = OrgOrgIdSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdSettingsAuditLogRoute =
  OrgOrgIdSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdSettingsApiKeysRoute = OrgOrgIdSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdDashboardDashboardIdRoute =
  OrgOrgIdDashboardDashboardIdRouteImport.update({
    id: '/dashboard/$dashboardId',
    path: '/dashboard/$dashboardId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdAccountsAccountIdRoute =
  OrgOrgIdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)
const OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute =
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport.update({
    id: '/resources/$pluginId/$resourceTypeId/$resourceId',
    path: '/resources/$pluginId/$resourceTypeId/$resourceId',
    getParentRoute: () => OrgOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/onboarding': typeof OnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/accounts/$accountId': typeof OrgOrgIdAccountsAccountIdRoute
  '/org/$orgId/dashboard/$dashboardId': typeof OrgOrgIdDashboardDashboardIdRoute
  '/org/$orgId/settings/api-keys': typeof OrgOrgIdSettingsApiKeysRoute
  '/org/$orgId/settings/audit-log': typeof OrgOrgIdSettingsAuditLogRoute
  '/org/$orgId/settings/billing': typeof OrgOrgIdSettingsBillingRoute
  '/org/$orgId/settings/team': typeof OrgOrgIdSettingsTeamRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/invite/$token'
    | '/org/$orgId'
    | '/org/$orgId/settings'
    | '/org/$orgId/'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/settings/'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/invite/$token'
    | '/org/$orgId'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/settings'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  id:
    | '__root__'
    | '/onboarding'
    | '/invite/$token'
    | '/org/$orgId'
    | '/org/$orgId/settings'
    | '/org/$orgId/'
    | '/org/$orgId/accounts/$accountId'
    | '/org/$orgId/dashboard/$dashboardId'
    | '/org/$orgId/settings/api-keys'
    | '/org/$orgId/settings/audit-log'
    | '/org/$orgId/settings/billing'
    | '/org/$orgId/settings/team'
    | '/org/$orgId/settings/'
    | '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OnboardingRoute: typeof OnboardingRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings': {
      id: '/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof OrgOrgIdSettingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings/': {
      id: '/org/$orgId/settings/'
      path: '/'
      fullPath: '/org/$orgId/settings/'
      preLoaderRoute: typeof OrgOrgIdSettingsIndexRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/team': {
      id: '/org/$orgId/settings/team'
      path: '/team'
      fullPath: '/org/$orgId/settings/team'
      preLoaderRoute: typeof OrgOrgIdSettingsTeamRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/billing': {
      id: '/org/$orgId/settings/billing'
      path: '/billing'
      fullPath: '/org/$orgId/settings/billing'
      preLoaderRoute: typeof OrgOrgIdSettingsBillingRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/audit-log': {
      id: '/org/$orgId/settings/audit-log'
      path: '/audit-log'
      fullPath: '/org/$orgId/settings/audit-log'
      preLoaderRoute: typeof OrgOrgIdSettingsAuditLogRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/settings/api-keys': {
      id: '/org/$orgId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/org/$orgId/settings/api-keys'
      preLoaderRoute: typeof OrgOrgIdSettingsApiKeysRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/dashboard/$dashboardId': {
      id: '/org/$orgId/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/org/$orgId/dashboard/$dashboardId'
      preLoaderRoute: typeof OrgOrgIdDashboardDashboardIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/accounts/$accountId': {
      id: '/org/$orgId/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/org/$orgId/accounts/$accountId'
      preLoaderRoute: typeof OrgOrgIdAccountsAccountIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId': {
      id: '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
      path: '/resources/$pluginId/$resourceTypeId/$resourceId'
      fullPath: '/org/$orgId/resources/$pluginId/$resourceTypeId/$resourceId'
      preLoaderRoute: typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
  }
}

interface OrgOrgIdSettingsRouteChildren {
  OrgOrgIdSettingsApiKeysRoute: typeof OrgOrgIdSettingsApiKeysRoute
  OrgOrgIdSettingsAuditLogRoute: typeof OrgOrgIdSettingsAuditLogRoute
  OrgOrgIdSettingsBillingRoute: typeof OrgOrgIdSettingsBillingRoute
  OrgOrgIdSettingsTeamRoute: typeof OrgOrgIdSettingsTeamRoute
  OrgOrgIdSettingsIndexRoute: typeof OrgOrgIdSettingsIndexRoute
}

const OrgOrgIdSettingsRouteChildren: OrgOrgIdSettingsRouteChildren = {
  OrgOrgIdSettingsApiKeysRoute: OrgOrgIdSettingsApiKeysRoute,
  OrgOrgIdSettingsAuditLogRoute: OrgOrgIdSettingsAuditLogRoute,
  OrgOrgIdSettingsBillingRoute: OrgOrgIdSettingsBillingRoute,
  OrgOrgIdSettingsTeamRoute: OrgOrgIdSettingsTeamRoute,
  OrgOrgIdSettingsIndexRoute: OrgOrgIdSettingsIndexRoute,
}

const OrgOrgIdSettingsRouteWithChildren =
  OrgOrgIdSettingsRoute._addFileChildren(OrgOrgIdSettingsRouteChildren)

interface OrgOrgIdRouteChildren {
  OrgOrgIdSettingsRoute: typeof OrgOrgIdSettingsRouteWithChildren
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdAccountsAccountIdRoute: typeof OrgOrgIdAccountsAccountIdRoute
  OrgOrgIdDashboardDashboardIdRoute: typeof OrgOrgIdDashboardDashboardIdRoute
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute: typeof OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdSettingsRoute: OrgOrgIdSettingsRouteWithChildren,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdAccountsAccountIdRoute: OrgOrgIdAccountsAccountIdRoute,
  OrgOrgIdDashboardDashboardIdRoute: OrgOrgIdDashboardDashboardIdRoute,
  OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute:
    OrgOrgIdResourcesPluginIdResourceTypeIdResourceIdRoute,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OnboardingRoute: OnboardingRoute,
  InviteTokenRoute: InviteTokenRoute,
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
