#!/usr/bin/env bash
#
# Cloud Agent install phase for the Infrawrench monorepo.
#
# Idempotent, source-derived setup only: refresh workspace dependencies and
# generated state. No services are started and no migrations run here (that is
# start.sh's job) — the system packages (Postgres, ClickHouse, the WorkOS
# emulator) come from the environment's base snapshot.
#
# Runs from the repo root after checkout, before start.sh.
set -euo pipefail

cd "$(dirname "$0")/.."

export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
corepack enable

# Workspace dependencies. Native modules (ssh2, node-pty…) build against the
# toolchain baked into the base image.
pnpm install --frozen-lockfile

# @infrawrench/desktop reads a gitignored env.ts; mirror CI by copying the
# production template so desktop typecheck/test/build work.
cp app/packages/desktop/env.production.ts app/packages/desktop/env.ts

# Local dev configuration for the server processes (web, poller,
# github-watcher). Dev-only fixed keys mirroring docker-compose.dev.yml — never
# reuse outside local dev. Gitignored; regenerated only when missing so a
# hand-edited file is preserved.
if [ ! -f app/packages/web/.env ]; then
  cat > app/packages/web/.env <<'ENV'
# Local Cloud Agent dev environment — generated by .cursor/install.sh.
# Dev-only fixed keys mirroring docker-compose.dev.yml. NEVER reuse elsewhere.
DATABASE_URL=postgres://infrawrench:infrawrench@localhost:5432/infrawrench
ENCRYPTION_MASTER_KEY=uRW8wQXfjwBUcLFwQnmNnO3VvY4x/Nd8E2VVQF9nnvo=

CLICKHOUSE_METRICS_URL=http://localhost:8123
CLICKHOUSE_METRICS_USER=default
CLICKHOUSE_METRICS_PASSWORD=infrawrench
CLICKHOUSE_METRICS_DATABASE=infrawrench

APP_URL=http://localhost:3000
INFRAWRENCH_PLATFORM_ADMIN_EMAILS=dev@infrawrench.local

# WorkOS emulator (github.com/workos/emulate) on localhost:4100
WORKOS_API_KEY=sk_test_default
WORKOS_CLIENT_ID=client_dev_emulator
WORKOS_API_HOSTNAME=localhost
WORKOS_API_PORT=4100
WORKOS_API_HTTPS=false
WORKOS_REDIRECT_URI=http://localhost:3000/callback
WORKOS_COOKIE_PASSWORD=9US946nJNfO1GgaWA3tog2kvIRDw9mBcaVVwMUyIeY0=
WORKOS_AUTHKIT_DOMAIN=http://localhost:4100
ENV
fi

# Warm the turbo build cache for the web app's workspace dependencies so the
# dev server boots without rebuilding 50+ packages. `pnpm --filter web dev`
# runs the dev script directly (not via `turbo run dev`), so it does not build
# ^deps itself. Cache replays instantly when nothing changed.
pnpm exec turbo run build --filter=@infrawrench/web^...

echo "[install] done"
