import type { RegionOption, SelectOption } from "@infrawrench/plugin-base";

/**
 * Regions the Cloud API accepts for a service (`ServicePostRequest.region`
 * enum in the ClickHouse Cloud OpenAPI spec, https://api.clickhouse.cloud/v1,
 * checked 2026-10). `availableFor` carries the provider so the create form's
 * region picker narrows to the provider the user picked.
 */
export const CLOUD_REGIONS: RegionOption[] = [
  // AWS
  {
    id: "us-east-1",
    label: "us-east-1",
    location: "N. Virginia, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["aws"],
  },
  {
    id: "us-east-2",
    label: "us-east-2",
    location: "Ohio, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["aws"],
  },
  {
    id: "us-west-2",
    label: "us-west-2",
    location: "Oregon, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["aws"],
  },
  {
    id: "ca-central-1",
    label: "ca-central-1",
    location: "Montreal, Canada",
    flag: "\u{1F1E8}\u{1F1E6}",
    availableFor: ["aws"],
  },
  {
    id: "eu-central-1",
    label: "eu-central-1",
    location: "Frankfurt, Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    availableFor: ["aws"],
  },
  {
    id: "eu-west-1",
    label: "eu-west-1",
    location: "Ireland",
    flag: "\u{1F1EE}\u{1F1EA}",
    availableFor: ["aws"],
  },
  {
    id: "eu-west-2",
    label: "eu-west-2",
    location: "London, UK",
    flag: "\u{1F1EC}\u{1F1E7}",
    availableFor: ["aws"],
  },
  {
    id: "il-central-1",
    label: "il-central-1",
    location: "Tel Aviv, Israel",
    flag: "\u{1F1EE}\u{1F1F1}",
    availableFor: ["aws"],
  },
  {
    id: "ap-south-1",
    label: "ap-south-1",
    location: "Mumbai, India",
    flag: "\u{1F1EE}\u{1F1F3}",
    availableFor: ["aws"],
  },
  {
    id: "ap-southeast-1",
    label: "ap-southeast-1",
    location: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
    availableFor: ["aws"],
  },
  {
    id: "ap-southeast-2",
    label: "ap-southeast-2",
    location: "Sydney, Australia",
    flag: "\u{1F1E6}\u{1F1FA}",
    availableFor: ["aws"],
  },
  {
    id: "ap-northeast-1",
    label: "ap-northeast-1",
    location: "Tokyo, Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
    availableFor: ["aws"],
  },
  {
    id: "ap-northeast-2",
    label: "ap-northeast-2",
    location: "Seoul, South Korea",
    flag: "\u{1F1F0}\u{1F1F7}",
    availableFor: ["aws"],
  },
  // GCP
  {
    id: "us-central1",
    label: "us-central1",
    location: "Iowa, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["gcp"],
  },
  {
    id: "us-east1",
    label: "us-east1",
    location: "South Carolina, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["gcp"],
  },
  {
    id: "europe-west2",
    label: "europe-west2",
    location: "London, UK",
    flag: "\u{1F1EC}\u{1F1E7}",
    availableFor: ["gcp"],
  },
  {
    id: "europe-west4",
    label: "europe-west4",
    location: "Netherlands",
    flag: "\u{1F1F3}\u{1F1F1}",
    availableFor: ["gcp"],
  },
  {
    id: "asia-southeast1",
    label: "asia-southeast1",
    location: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
    availableFor: ["gcp"],
  },
  {
    id: "asia-northeast1",
    label: "asia-northeast1",
    location: "Tokyo, Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
    availableFor: ["gcp"],
  },
  // Azure
  {
    id: "eastus",
    label: "eastus",
    location: "Virginia, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["azure"],
  },
  {
    id: "eastus2",
    label: "eastus2",
    location: "Virginia, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["azure"],
  },
  {
    id: "centralus",
    label: "centralus",
    location: "Iowa, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["azure"],
  },
  {
    id: "westus3",
    label: "westus3",
    location: "Arizona, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
    availableFor: ["azure"],
  },
  {
    id: "germanywestcentral",
    label: "germanywestcentral",
    location: "Frankfurt, Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    availableFor: ["azure"],
  },
];

/**
 * Managed Postgres VM sizes (`pgSize` enum in the same spec). AWS sizes are
 * EC2 instance types (`family.size`), GCP sizes are machine types
 * (`family-shape-vcpus`), so the separator tells them apart.
 */
const POSTGRES_SIZES = [
  "r8gd.medium",
  "r8gd.large",
  "r8gd.xlarge",
  "r8gd.2xlarge",
  "r8gd.4xlarge",
  "r8gd.8xlarge",
  "r8gd.12xlarge",
  "r8gd.16xlarge",
  "r8gd.24xlarge",
  "r8gd.48xlarge",
  "r6gd.medium",
  "r6gd.large",
  "r6gd.xlarge",
  "r6gd.2xlarge",
  "r6gd.4xlarge",
  "r6gd.8xlarge",
  "r6gd.12xlarge",
  "r6gd.16xlarge",
  "r6id.large",
  "r6id.xlarge",
  "r6id.2xlarge",
  "r6id.4xlarge",
  "r6id.8xlarge",
  "r6id.12xlarge",
  "r6id.16xlarge",
  "r6id.24xlarge",
  "r6id.32xlarge",
  "m8gd.large",
  "m8gd.xlarge",
  "m8gd.2xlarge",
  "m8gd.4xlarge",
  "m8gd.8xlarge",
  "m8gd.16xlarge",
  "m6gd.large",
  "m6gd.xlarge",
  "m6gd.2xlarge",
  "m6gd.4xlarge",
  "m6gd.8xlarge",
  "m6gd.16xlarge",
  "m6id.large",
  "m6id.xlarge",
  "m6id.2xlarge",
  "m6id.4xlarge",
  "m6id.8xlarge",
  "m6id.16xlarge",
  "c6gd.large",
  "c6gd.xlarge",
  "c6gd.2xlarge",
  "c6gd.4xlarge",
  "c6gd.8xlarge",
  "c6gd.16xlarge",
  "i8g.large",
  "i8g.xlarge",
  "i8g.2xlarge",
  "i8g.4xlarge",
  "i8g.8xlarge",
  "i8g.16xlarge",
  "i8g.24xlarge",
  "i8ge.large",
  "i8ge.xlarge",
  "i8ge.2xlarge",
  "i8ge.3xlarge",
  "i8ge.6xlarge",
  "i8ge.12xlarge",
  "i8ge.18xlarge",
  "i8ge.24xlarge",
  "i7i.large",
  "i7i.xlarge",
  "i7i.2xlarge",
  "i7i.4xlarge",
  "i7i.8xlarge",
  "i7i.12xlarge",
  "i7i.16xlarge",
  "i7i.24xlarge",
  "i7ie.large",
  "i7ie.xlarge",
  "i7ie.2xlarge",
  "i7ie.3xlarge",
  "i7ie.6xlarge",
  "i7ie.12xlarge",
  "i7ie.18xlarge",
  "i7ie.24xlarge",
  "c4a-highmem-4",
  "c4a-highmem-8",
  "c4a-highmem-16",
  "c4a-highmem-32",
  "c4a-highmem-48",
  "c4a-highmem-64",
  "c4a-highmem-72",
  "c4a-standard-4",
  "c4a-standard-8",
  "c4a-standard-16",
  "c4a-standard-32",
  "c4a-standard-48",
  "c4a-standard-64",
  "c4a-standard-72",
  "c4-highmem-4",
  "c4-highmem-8",
  "c4-highmem-16",
  "c4-highmem-24",
  "c4-highmem-32",
  "c4-highmem-48",
  "c4-highmem-96",
  "c4-highmem-144",
  "c4-highmem-192",
  "c4-highmem-288",
  "c4-standard-4",
  "c4-standard-8",
  "c4-standard-16",
  "c4-standard-24",
  "c4-standard-32",
  "c4-standard-48",
  "c4-standard-96",
  "c4-standard-144",
  "c4-standard-192",
  "c4-standard-288",
  "c4d-highmem-8",
  "c4d-highmem-16",
  "c4d-highmem-32",
  "c4d-highmem-48",
  "c4d-highmem-64",
  "c4d-highmem-96",
  "c4d-highmem-192",
  "c4d-highmem-384",
  "c4d-standard-8",
  "c4d-standard-16",
  "c4d-standard-32",
  "c4d-standard-48",
  "c4d-standard-64",
  "c4d-standard-96",
  "c4d-standard-192",
  "c4d-standard-384",
  "z3-highlssd-8",
  "z3-highlssd-16",
  "z3-highlssd-22",
  "z3-highlssd-32",
  "z3-highlssd-44",
  "z3-highlssd-88",
  "z3-standardlssd-14",
  "z3-standardlssd-22",
  "z3-standardlssd-44",
  "z3-standardlssd-88",
  "z3-standardlssd-176",
];

export function postgresSizeProvider(size: string): "aws" | "gcp" {
  return size.includes(".") ? "aws" : "gcp";
}

export function postgresSizeOptions(provider: "aws" | "gcp"): SelectOption[] {
  return POSTGRES_SIZES.filter((s) => postgresSizeProvider(s) === provider).map((s) => ({
    id: s,
    label: s,
  }));
}
