import type { RegionOption, SizeOption } from "@infrawrench/plugin-base";

export const AWS_REGIONS: RegionOption[] = [
  {
    id: "us-east-1",
    label: "us-east-1",
    location: "N. Virginia, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
  },
  { id: "us-east-2", label: "us-east-2", location: "Ohio, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  {
    id: "us-west-1",
    label: "us-west-1",
    location: "N. California, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
  },
  { id: "us-west-2", label: "us-west-2", location: "Oregon, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  {
    id: "ca-central-1",
    label: "ca-central-1",
    location: "Montreal, Canada",
    flag: "\u{1F1E8}\u{1F1E6}",
  },
  { id: "eu-west-1", label: "eu-west-1", location: "Ireland", flag: "\u{1F1EE}\u{1F1EA}" },
  { id: "eu-west-2", label: "eu-west-2", location: "London, UK", flag: "\u{1F1EC}\u{1F1E7}" },
  { id: "eu-west-3", label: "eu-west-3", location: "Paris, France", flag: "\u{1F1EB}\u{1F1F7}" },
  {
    id: "eu-central-1",
    label: "eu-central-1",
    location: "Frankfurt, Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
  },
  {
    id: "eu-central-2",
    label: "eu-central-2",
    location: "Zurich, Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
  },
  {
    id: "eu-north-1",
    label: "eu-north-1",
    location: "Stockholm, Sweden",
    flag: "\u{1F1F8}\u{1F1EA}",
  },
  { id: "eu-south-1", label: "eu-south-1", location: "Milan, Italy", flag: "\u{1F1EE}\u{1F1F9}" },
  { id: "eu-south-2", label: "eu-south-2", location: "Spain", flag: "\u{1F1EA}\u{1F1F8}" },
  {
    id: "ap-southeast-1",
    label: "ap-southeast-1",
    location: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
  },
  {
    id: "ap-southeast-2",
    label: "ap-southeast-2",
    location: "Sydney, Australia",
    flag: "\u{1F1E6}\u{1F1FA}",
  },
  {
    id: "ap-southeast-3",
    label: "ap-southeast-3",
    location: "Jakarta, Indonesia",
    flag: "\u{1F1EE}\u{1F1E9}",
  },
  {
    id: "ap-northeast-1",
    label: "ap-northeast-1",
    location: "Tokyo, Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
  },
  {
    id: "ap-northeast-2",
    label: "ap-northeast-2",
    location: "Seoul, South Korea",
    flag: "\u{1F1F0}\u{1F1F7}",
  },
  {
    id: "ap-northeast-3",
    label: "ap-northeast-3",
    location: "Osaka, Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
  },
  {
    id: "ap-south-1",
    label: "ap-south-1",
    location: "Mumbai, India",
    flag: "\u{1F1EE}\u{1F1F3}",
  },
  {
    id: "ap-south-2",
    label: "ap-south-2",
    location: "Hyderabad, India",
    flag: "\u{1F1EE}\u{1F1F3}",
  },
  { id: "ap-east-1", label: "ap-east-1", location: "Hong Kong", flag: "\u{1F1ED}\u{1F1F0}" },
  {
    id: "sa-east-1",
    label: "sa-east-1",
    location: "São Paulo, Brazil",
    flag: "\u{1F1E7}\u{1F1F7}",
  },
  { id: "me-south-1", label: "me-south-1", location: "Bahrain", flag: "\u{1F1E7}\u{1F1ED}" },
  { id: "me-central-1", label: "me-central-1", location: "UAE", flag: "\u{1F1E6}\u{1F1EA}" },
  {
    id: "af-south-1",
    label: "af-south-1",
    location: "Cape Town, South Africa",
    flag: "\u{1F1FF}\u{1F1E6}",
  },
  {
    id: "il-central-1",
    label: "il-central-1",
    location: "Tel Aviv, Israel",
    flag: "\u{1F1EE}\u{1F1F1}",
  },
];

// Curated EC2 instance-type catalogue.
//
// Current-generation families per the EC2 Instance Types index
// (https://instances.vantage.sh/, mid-2026): generations 7 and 8 are the
// mainstream current-gen; t3/t4g are still the only Burstable options.
//
// Architecture hint follows the suffix convention:
//   *g  → AWS Graviton (arm64)
//   *a  → AMD EPYC (x86_64)
//   *i  → Intel Xeon (x86_64)
//
// `instanceTypeArch` in ami-lookup.ts derives the correct AMI architecture
// at create time based on the family.
export const EC2_SIZES: SizeOption[] = [
  // Burstable — t4g is Graviton2, t3a is AMD, t3 is Intel.
  {
    id: "t4g.nano",
    label: "t4g.nano",
    vcpus: 2,
    memoryMb: 512,
    category: "T4g · Burstable (arm64)",
  },
  {
    id: "t4g.micro",
    label: "t4g.micro",
    vcpus: 2,
    memoryMb: 1024,
    category: "T4g · Burstable (arm64)",
  },
  {
    id: "t4g.small",
    label: "t4g.small",
    vcpus: 2,
    memoryMb: 2048,
    category: "T4g · Burstable (arm64)",
  },
  {
    id: "t4g.medium",
    label: "t4g.medium",
    vcpus: 2,
    memoryMb: 4096,
    category: "T4g · Burstable (arm64)",
  },
  {
    id: "t4g.large",
    label: "t4g.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "T4g · Burstable (arm64)",
  },
  {
    id: "t4g.xlarge",
    label: "t4g.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "T4g · Burstable (arm64)",
  },
  {
    id: "t4g.2xlarge",
    label: "t4g.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "T4g · Burstable (arm64)",
  },
  { id: "t3.nano", label: "t3.nano", vcpus: 2, memoryMb: 512, category: "T3 · Burstable (Intel)" },
  {
    id: "t3.micro",
    label: "t3.micro",
    vcpus: 2,
    memoryMb: 1024,
    category: "T3 · Burstable (Intel)",
  },
  {
    id: "t3.small",
    label: "t3.small",
    vcpus: 2,
    memoryMb: 2048,
    category: "T3 · Burstable (Intel)",
  },
  {
    id: "t3.medium",
    label: "t3.medium",
    vcpus: 2,
    memoryMb: 4096,
    category: "T3 · Burstable (Intel)",
  },
  {
    id: "t3.large",
    label: "t3.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "T3 · Burstable (Intel)",
  },
  {
    id: "t3.xlarge",
    label: "t3.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "T3 · Burstable (Intel)",
  },
  {
    id: "t3.2xlarge",
    label: "t3.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "T3 · Burstable (Intel)",
  },

  // General purpose — m8g (Graviton4), m8i (Intel), m8a (AMD). m7* still
  // common in some regions; m6 is one gen behind but still widely deployed.
  {
    id: "m8g.large",
    label: "m8g.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "M8g · General purpose (Graviton4)",
  },
  {
    id: "m8g.xlarge",
    label: "m8g.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "M8g · General purpose (Graviton4)",
  },
  {
    id: "m8g.2xlarge",
    label: "m8g.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "M8g · General purpose (Graviton4)",
  },
  {
    id: "m8g.4xlarge",
    label: "m8g.4xlarge",
    vcpus: 16,
    memoryMb: 65536,
    category: "M8g · General purpose (Graviton4)",
  },
  {
    id: "m8g.8xlarge",
    label: "m8g.8xlarge",
    vcpus: 32,
    memoryMb: 131072,
    category: "M8g · General purpose (Graviton4)",
  },
  {
    id: "m8i.large",
    label: "m8i.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "M8i · General purpose (Intel)",
  },
  {
    id: "m8i.xlarge",
    label: "m8i.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "M8i · General purpose (Intel)",
  },
  {
    id: "m8i.2xlarge",
    label: "m8i.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "M8i · General purpose (Intel)",
  },
  {
    id: "m8i.4xlarge",
    label: "m8i.4xlarge",
    vcpus: 16,
    memoryMb: 65536,
    category: "M8i · General purpose (Intel)",
  },
  {
    id: "m8a.large",
    label: "m8a.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "M8a · General purpose (AMD)",
  },
  {
    id: "m8a.xlarge",
    label: "m8a.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "M8a · General purpose (AMD)",
  },
  {
    id: "m8a.2xlarge",
    label: "m8a.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "M8a · General purpose (AMD)",
  },
  {
    id: "m8a.4xlarge",
    label: "m8a.4xlarge",
    vcpus: 16,
    memoryMb: 65536,
    category: "M8a · General purpose (AMD)",
  },
  {
    id: "m7g.large",
    label: "m7g.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "M7g · General purpose (Graviton3)",
  },
  {
    id: "m7g.xlarge",
    label: "m7g.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "M7g · General purpose (Graviton3)",
  },
  {
    id: "m7g.2xlarge",
    label: "m7g.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "M7g · General purpose (Graviton3)",
  },
  {
    id: "m7i.large",
    label: "m7i.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "M7i · General purpose (Intel)",
  },
  {
    id: "m7i.xlarge",
    label: "m7i.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "M7i · General purpose (Intel)",
  },
  {
    id: "m7i.2xlarge",
    label: "m7i.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "M7i · General purpose (Intel)",
  },

  // Compute optimized — c8g (Graviton4), c8i (Intel), c8a (AMD).
  {
    id: "c8g.large",
    label: "c8g.large",
    vcpus: 2,
    memoryMb: 4096,
    category: "C8g · Compute-optimized (Graviton4)",
  },
  {
    id: "c8g.xlarge",
    label: "c8g.xlarge",
    vcpus: 4,
    memoryMb: 8192,
    category: "C8g · Compute-optimized (Graviton4)",
  },
  {
    id: "c8g.2xlarge",
    label: "c8g.2xlarge",
    vcpus: 8,
    memoryMb: 16384,
    category: "C8g · Compute-optimized (Graviton4)",
  },
  {
    id: "c8g.4xlarge",
    label: "c8g.4xlarge",
    vcpus: 16,
    memoryMb: 32768,
    category: "C8g · Compute-optimized (Graviton4)",
  },
  {
    id: "c8i.large",
    label: "c8i.large",
    vcpus: 2,
    memoryMb: 4096,
    category: "C8i · Compute-optimized (Intel)",
  },
  {
    id: "c8i.xlarge",
    label: "c8i.xlarge",
    vcpus: 4,
    memoryMb: 8192,
    category: "C8i · Compute-optimized (Intel)",
  },
  {
    id: "c8i.2xlarge",
    label: "c8i.2xlarge",
    vcpus: 8,
    memoryMb: 16384,
    category: "C8i · Compute-optimized (Intel)",
  },
  {
    id: "c8i.4xlarge",
    label: "c8i.4xlarge",
    vcpus: 16,
    memoryMb: 32768,
    category: "C8i · Compute-optimized (Intel)",
  },
  {
    id: "c8a.large",
    label: "c8a.large",
    vcpus: 2,
    memoryMb: 4096,
    category: "C8a · Compute-optimized (AMD)",
  },
  {
    id: "c8a.xlarge",
    label: "c8a.xlarge",
    vcpus: 4,
    memoryMb: 8192,
    category: "C8a · Compute-optimized (AMD)",
  },
  {
    id: "c8a.2xlarge",
    label: "c8a.2xlarge",
    vcpus: 8,
    memoryMb: 16384,
    category: "C8a · Compute-optimized (AMD)",
  },
  {
    id: "c7g.large",
    label: "c7g.large",
    vcpus: 2,
    memoryMb: 4096,
    category: "C7g · Compute-optimized (Graviton3)",
  },
  {
    id: "c7g.xlarge",
    label: "c7g.xlarge",
    vcpus: 4,
    memoryMb: 8192,
    category: "C7g · Compute-optimized (Graviton3)",
  },
  {
    id: "c7g.2xlarge",
    label: "c7g.2xlarge",
    vcpus: 8,
    memoryMb: 16384,
    category: "C7g · Compute-optimized (Graviton3)",
  },
  {
    id: "c7i.large",
    label: "c7i.large",
    vcpus: 2,
    memoryMb: 4096,
    category: "C7i · Compute-optimized (Intel)",
  },
  {
    id: "c7i.xlarge",
    label: "c7i.xlarge",
    vcpus: 4,
    memoryMb: 8192,
    category: "C7i · Compute-optimized (Intel)",
  },
  {
    id: "c7i.2xlarge",
    label: "c7i.2xlarge",
    vcpus: 8,
    memoryMb: 16384,
    category: "C7i · Compute-optimized (Intel)",
  },

  // Memory optimized — r8g (Graviton4), r8i (Intel), r8a (AMD).
  {
    id: "r8g.large",
    label: "r8g.large",
    vcpus: 2,
    memoryMb: 16384,
    category: "R8g · Memory-optimized (Graviton4)",
  },
  {
    id: "r8g.xlarge",
    label: "r8g.xlarge",
    vcpus: 4,
    memoryMb: 32768,
    category: "R8g · Memory-optimized (Graviton4)",
  },
  {
    id: "r8g.2xlarge",
    label: "r8g.2xlarge",
    vcpus: 8,
    memoryMb: 65536,
    category: "R8g · Memory-optimized (Graviton4)",
  },
  {
    id: "r8g.4xlarge",
    label: "r8g.4xlarge",
    vcpus: 16,
    memoryMb: 131072,
    category: "R8g · Memory-optimized (Graviton4)",
  },
  {
    id: "r8i.large",
    label: "r8i.large",
    vcpus: 2,
    memoryMb: 16384,
    category: "R8i · Memory-optimized (Intel)",
  },
  {
    id: "r8i.xlarge",
    label: "r8i.xlarge",
    vcpus: 4,
    memoryMb: 32768,
    category: "R8i · Memory-optimized (Intel)",
  },
  {
    id: "r8i.2xlarge",
    label: "r8i.2xlarge",
    vcpus: 8,
    memoryMb: 65536,
    category: "R8i · Memory-optimized (Intel)",
  },
  {
    id: "r8i.4xlarge",
    label: "r8i.4xlarge",
    vcpus: 16,
    memoryMb: 131072,
    category: "R8i · Memory-optimized (Intel)",
  },
  {
    id: "r8a.large",
    label: "r8a.large",
    vcpus: 2,
    memoryMb: 16384,
    category: "R8a · Memory-optimized (AMD)",
  },
  {
    id: "r8a.xlarge",
    label: "r8a.xlarge",
    vcpus: 4,
    memoryMb: 32768,
    category: "R8a · Memory-optimized (AMD)",
  },
  {
    id: "r8a.2xlarge",
    label: "r8a.2xlarge",
    vcpus: 8,
    memoryMb: 65536,
    category: "R8a · Memory-optimized (AMD)",
  },
  {
    id: "r7g.large",
    label: "r7g.large",
    vcpus: 2,
    memoryMb: 16384,
    category: "R7g · Memory-optimized (Graviton3)",
  },
  {
    id: "r7g.xlarge",
    label: "r7g.xlarge",
    vcpus: 4,
    memoryMb: 32768,
    category: "R7g · Memory-optimized (Graviton3)",
  },
  {
    id: "r7g.2xlarge",
    label: "r7g.2xlarge",
    vcpus: 8,
    memoryMb: 65536,
    category: "R7g · Memory-optimized (Graviton3)",
  },
];

/**
 * The exact `sshAccess` string the EC2 lister stores when an attached security
 * group opens TCP/22 to 0.0.0.0/0 (or ::/0). The `ec2-ssh-world-open` posture
 * check matches this field with `equals`, so both sides must reference this
 * constant — copy drift would silently disarm the check.
 */
export const EC2_SSH_WORLD_OPEN = "Port 22 open to the world (0.0.0.0/0).";
