import type { RegionOption, SizeOption } from "@infrawrench/plugin-base";

export const AWS_REGIONS: RegionOption[] = [
  {
    id: "us-east-1",
    label: "us-east-1",
    location: "N. Virginia, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
  },
  { id: "us-east-2", label: "us-east-2", location: "Ohio, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  {
    id: "us-west-1",
    label: "us-west-1",
    location: "N. California, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
  },
  { id: "us-west-2", label: "us-west-2", location: "Oregon, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  {
    id: "ca-central-1",
    label: "ca-central-1",
    location: "Montreal, Canada",
    flag: "\u{1F1E8}\u{1F1E6}",
  },
  { id: "eu-west-1", label: "eu-west-1", location: "Ireland", flag: "\u{1F1EE}\u{1F1EA}" },
  { id: "eu-west-2", label: "eu-west-2", location: "London, UK", flag: "\u{1F1EC}\u{1F1E7}" },
  { id: "eu-west-3", label: "eu-west-3", location: "Paris, France", flag: "\u{1F1EB}\u{1F1F7}" },
  {
    id: "eu-central-1",
    label: "eu-central-1",
    location: "Frankfurt, Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
  },
  {
    id: "eu-central-2",
    label: "eu-central-2",
    location: "Zurich, Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
  },
  {
    id: "eu-north-1",
    label: "eu-north-1",
    location: "Stockholm, Sweden",
    flag: "\u{1F1F8}\u{1F1EA}",
  },
  { id: "eu-south-1", label: "eu-south-1", location: "Milan, Italy", flag: "\u{1F1EE}\u{1F1F9}" },
  { id: "eu-south-2", label: "eu-south-2", location: "Spain", flag: "\u{1F1EA}\u{1F1F8}" },
  {
    id: "ap-southeast-1",
    label: "ap-southeast-1",
    location: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
  },
  {
    id: "ap-southeast-2",
    label: "ap-southeast-2",
    location: "Sydney, Australia",
    flag: "\u{1F1E6}\u{1F1FA}",
  },
  {
    id: "ap-southeast-3",
    label: "ap-southeast-3",
    location: "Jakarta, Indonesia",
    flag: "\u{1F1EE}\u{1F1E9}",
  },
  {
    id: "ap-northeast-1",
    label: "ap-northeast-1",
    location: "Tokyo, Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
  },
  {
    id: "ap-northeast-2",
    label: "ap-northeast-2",
    location: "Seoul, South Korea",
    flag: "\u{1F1F0}\u{1F1F7}",
  },
  {
    id: "ap-northeast-3",
    label: "ap-northeast-3",
    location: "Osaka, Japan",
    flag: "\u{1F1EF}\u{1F1F5}",
  },
  {
    id: "ap-south-1",
    label: "ap-south-1",
    location: "Mumbai, India",
    flag: "\u{1F1EE}\u{1F1F3}",
  },
  {
    id: "ap-south-2",
    label: "ap-south-2",
    location: "Hyderabad, India",
    flag: "\u{1F1EE}\u{1F1F3}",
  },
  { id: "ap-east-1", label: "ap-east-1", location: "Hong Kong", flag: "\u{1F1ED}\u{1F1F0}" },
  {
    id: "sa-east-1",
    label: "sa-east-1",
    location: "São Paulo, Brazil",
    flag: "\u{1F1E7}\u{1F1F7}",
  },
  { id: "me-south-1", label: "me-south-1", location: "Bahrain", flag: "\u{1F1E7}\u{1F1ED}" },
  { id: "me-central-1", label: "me-central-1", location: "UAE", flag: "\u{1F1E6}\u{1F1EA}" },
  {
    id: "af-south-1",
    label: "af-south-1",
    location: "Cape Town, South Africa",
    flag: "\u{1F1FF}\u{1F1E6}",
  },
  {
    id: "il-central-1",
    label: "il-central-1",
    location: "Tel Aviv, Israel",
    flag: "\u{1F1EE}\u{1F1F1}",
  },
];

export const EC2_SIZES: SizeOption[] = [
  // T3 burstable
  { id: "t3.nano", label: "t3.nano", vcpus: 2, memoryMb: 512, category: "T3 · Burstable" },
  { id: "t3.micro", label: "t3.micro", vcpus: 2, memoryMb: 1024, category: "T3 · Burstable" },
  { id: "t3.small", label: "t3.small", vcpus: 2, memoryMb: 2048, category: "T3 · Burstable" },
  { id: "t3.medium", label: "t3.medium", vcpus: 2, memoryMb: 4096, category: "T3 · Burstable" },
  { id: "t3.large", label: "t3.large", vcpus: 2, memoryMb: 8192, category: "T3 · Burstable" },
  { id: "t3.xlarge", label: "t3.xlarge", vcpus: 4, memoryMb: 16384, category: "T3 · Burstable" },
  {
    id: "t3.2xlarge",
    label: "t3.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "T3 · Burstable",
  },
  // M6i general purpose
  {
    id: "m6i.large",
    label: "m6i.large",
    vcpus: 2,
    memoryMb: 8192,
    category: "M6i · General purpose",
  },
  {
    id: "m6i.xlarge",
    label: "m6i.xlarge",
    vcpus: 4,
    memoryMb: 16384,
    category: "M6i · General purpose",
  },
  {
    id: "m6i.2xlarge",
    label: "m6i.2xlarge",
    vcpus: 8,
    memoryMb: 32768,
    category: "M6i · General purpose",
  },
  {
    id: "m6i.4xlarge",
    label: "m6i.4xlarge",
    vcpus: 16,
    memoryMb: 65536,
    category: "M6i · General purpose",
  },
  {
    id: "m6i.8xlarge",
    label: "m6i.8xlarge",
    vcpus: 32,
    memoryMb: 131072,
    category: "M6i · General purpose",
  },
  // C6i compute-optimized
  {
    id: "c6i.large",
    label: "c6i.large",
    vcpus: 2,
    memoryMb: 4096,
    category: "C6i · Compute-optimized",
  },
  {
    id: "c6i.xlarge",
    label: "c6i.xlarge",
    vcpus: 4,
    memoryMb: 8192,
    category: "C6i · Compute-optimized",
  },
  {
    id: "c6i.2xlarge",
    label: "c6i.2xlarge",
    vcpus: 8,
    memoryMb: 16384,
    category: "C6i · Compute-optimized",
  },
  {
    id: "c6i.4xlarge",
    label: "c6i.4xlarge",
    vcpus: 16,
    memoryMb: 32768,
    category: "C6i · Compute-optimized",
  },
  // R6i memory-optimized
  {
    id: "r6i.large",
    label: "r6i.large",
    vcpus: 2,
    memoryMb: 16384,
    category: "R6i · Memory-optimized",
  },
  {
    id: "r6i.xlarge",
    label: "r6i.xlarge",
    vcpus: 4,
    memoryMb: 32768,
    category: "R6i · Memory-optimized",
  },
  {
    id: "r6i.2xlarge",
    label: "r6i.2xlarge",
    vcpus: 8,
    memoryMb: 65536,
    category: "R6i · Memory-optimized",
  },
  {
    id: "r6i.4xlarge",
    label: "r6i.4xlarge",
    vcpus: 16,
    memoryMb: 131072,
    category: "R6i · Memory-optimized",
  },
];
