import type { FocusCapabilityDeclaration } from "@infrawrench/plugin-base";

/**
 * How AWS services map onto the FOCUS service taxonomy. The names are Cost
 * Explorer's `SERVICE` dimension values (e.g. `Amazon Elastic Compute Cloud -
 * Compute`, `AWS Lambda`).
 *
 * Read by FOCUS-schema cost exports to fill `ServiceCategory` and
 * `ServiceSubcategory` (FOCUS v1.3 allowed values; the manifest schema rejects
 * a pair that is not). Rules match case-insensitively as substrings of the
 * `service` this plugin writes, first match wins, so specific names come
 * before the general ones that would also match them. A service no rule names
 * falls through to the host's generic keyword classifier, then to `Other`.
 */
export const AWS_FOCUS: FocusCapabilityDeclaration = {
  services: [
    {
      match: "Elastic Container Registry",
      category: "Developer Tools",
      subcategory: "Developer Platforms",
    },
    {
      match: "Elastic Container Service for Kubernetes",
      category: "Compute",
      subcategory: "Containers",
    },
    { match: "Elastic Kubernetes Service", category: "Compute", subcategory: "Containers" },
    { match: "EC2 Container Service", category: "Compute", subcategory: "Containers" },
    { match: "Elastic Container Service", category: "Compute", subcategory: "Containers" },
    { match: "Fargate", category: "Compute", subcategory: "Containers" },
    { match: "App Runner", category: "Web", subcategory: "Application Platforms" },
    { match: "Elastic Compute Cloud", category: "Compute", subcategory: "Virtual Machines" },
    { match: "EC2 - Other", category: "Compute", subcategory: "Other (Compute)" },
    { match: "Lightsail", category: "Compute", subcategory: "Virtual Machines" },
    { match: "Lambda", category: "Compute", subcategory: "Serverless Compute" },
    { match: "AWS Batch", category: "Compute", subcategory: "Other (Compute)" },
    { match: "WorkSpaces", category: "Compute", subcategory: "End User Computing" },
    { match: "AppStream", category: "Compute", subcategory: "End User Computing" },
    { match: "Braket", category: "Compute", subcategory: "Quantum Compute" },
    { match: "Elastic Block Store", category: "Storage", subcategory: "Block Storage" },
    { match: "Elastic File System", category: "Storage", subcategory: "File Storage" },
    { match: "FSx", category: "Storage", subcategory: "File Storage" },
    { match: "Glacier", category: "Storage", subcategory: "Backup Storage" },
    { match: "Simple Storage Service", category: "Storage", subcategory: "Object Storage" },
    { match: "AWS Backup", category: "Storage", subcategory: "Backup Storage" },
    { match: "Storage Gateway", category: "Storage", subcategory: "Storage Platforms" },
    {
      match: "Elastic Disaster Recovery",
      category: "Management and Governance",
      subcategory: "Disaster Recovery",
    },
    { match: "Aurora", category: "Databases", subcategory: "Relational Databases" },
    {
      match: "Relational Database Service",
      category: "Databases",
      subcategory: "Relational Databases",
    },
    { match: "DynamoDB", category: "Databases", subcategory: "NoSQL Databases" },
    { match: "DocumentDB", category: "Databases", subcategory: "NoSQL Databases" },
    { match: "Keyspaces", category: "Databases", subcategory: "NoSQL Databases" },
    { match: "Neptune", category: "Databases", subcategory: "Other (Databases)" },
    { match: "Timestream", category: "Databases", subcategory: "Time Series Databases" },
    { match: "ElastiCache", category: "Databases", subcategory: "Caching" },
    { match: "MemoryDB", category: "Databases", subcategory: "Caching" },
    { match: "Redshift", category: "Databases", subcategory: "Data Warehouses" },
    { match: "Quantum Ledger", category: "Databases", subcategory: "Ledger Databases" },
    { match: "Bedrock", category: "AI and Machine Learning", subcategory: "Generative AI" },
    { match: "Amazon Q", category: "AI and Machine Learning", subcategory: "Generative AI" },
    { match: "SageMaker", category: "AI and Machine Learning", subcategory: "Machine Learning" },
    {
      match: "Comprehend",
      category: "AI and Machine Learning",
      subcategory: "Natural Language Processing",
    },
    {
      match: "Transcribe",
      category: "AI and Machine Learning",
      subcategory: "Natural Language Processing",
    },
    {
      match: "Translate",
      category: "AI and Machine Learning",
      subcategory: "Natural Language Processing",
    },
    {
      match: "Polly",
      category: "AI and Machine Learning",
      subcategory: "Natural Language Processing",
    },
    { match: "Textract", category: "AI and Machine Learning", subcategory: "Machine Learning" },
    { match: "Rekognition", category: "AI and Machine Learning", subcategory: "Machine Learning" },
    { match: "Amazon Lex", category: "AI and Machine Learning", subcategory: "Bots" },
    { match: "Kendra", category: "Analytics", subcategory: "Search" },
    { match: "OpenSearch", category: "Analytics", subcategory: "Search" },
    { match: "Elasticsearch", category: "Analytics", subcategory: "Search" },
    { match: "Athena", category: "Analytics", subcategory: "Data Processing" },
    { match: "AWS Glue", category: "Analytics", subcategory: "Data Processing" },
    { match: "Elastic MapReduce", category: "Analytics", subcategory: "Data Processing" },
    { match: "Kinesis", category: "Analytics", subcategory: "Streaming Analytics" },
    {
      match: "Managed Streaming for Apache Kafka",
      category: "Analytics",
      subcategory: "Streaming Analytics",
    },
    { match: "QuickSight", category: "Analytics", subcategory: "Business Intelligence" },
    {
      match: "Lake Formation",
      category: "Management and Governance",
      subcategory: "Data Governance",
    },
    { match: "DataZone", category: "Management and Governance", subcategory: "Data Governance" },
    { match: "Simple Queue Service", category: "Integration", subcategory: "Messaging" },
    { match: "Simple Notification Service", category: "Integration", subcategory: "Messaging" },
    { match: "Amazon MQ", category: "Integration", subcategory: "Messaging" },
    { match: "EventBridge", category: "Integration", subcategory: "Messaging" },
    { match: "CloudWatch Events", category: "Integration", subcategory: "Messaging" },
    { match: "Step Functions", category: "Integration", subcategory: "Workflow Orchestration" },
    {
      match: "Managed Workflows for Apache Airflow",
      category: "Integration",
      subcategory: "Workflow Orchestration",
    },
    { match: "API Gateway", category: "Integration", subcategory: "API Management" },
    { match: "AppSync", category: "Integration", subcategory: "API Management" },
    {
      match: "Simple Email Service",
      category: "Business Applications",
      subcategory: "Other (Business Applications)",
    },
    {
      match: "Pinpoint",
      category: "Business Applications",
      subcategory: "Other (Business Applications)",
    },
    {
      match: "Amazon Connect",
      category: "Business Applications",
      subcategory: "Productivity and Collaboration",
    },
    {
      match: "WorkMail",
      category: "Business Applications",
      subcategory: "Productivity and Collaboration",
    },
    {
      match: "Chime",
      category: "Business Applications",
      subcategory: "Productivity and Collaboration",
    },
    { match: "CloudFront", category: "Networking", subcategory: "Content Delivery" },
    { match: "Route 53", category: "Networking", subcategory: "Network Routing" },
    { match: "Global Accelerator", category: "Networking", subcategory: "Application Networking" },
    {
      match: "Elastic Load Balancing",
      category: "Networking",
      subcategory: "Application Networking",
    },
    {
      match: "Virtual Private Cloud",
      category: "Networking",
      subcategory: "Network Infrastructure",
    },
    { match: "Direct Connect", category: "Networking", subcategory: "Network Connectivity" },
    { match: "Transit Gateway", category: "Networking", subcategory: "Network Connectivity" },
    { match: "PrivateLink", category: "Networking", subcategory: "Network Connectivity" },
    { match: "VPN", category: "Networking", subcategory: "Network Connectivity" },
    { match: "Data Transfer", category: "Networking", subcategory: "Network Infrastructure" },
    { match: "Network Firewall", category: "Networking", subcategory: "Network Security" },
    { match: "AWS WAF", category: "Networking", subcategory: "Network Security" },
    { match: "AWS Shield", category: "Networking", subcategory: "Network Security" },
    { match: "GuardDuty", category: "Security", subcategory: "Threat Detection and Response" },
    {
      match: "Amazon Detective",
      category: "Security",
      subcategory: "Threat Detection and Response",
    },
    { match: "Inspector", category: "Security", subcategory: "Security Posture Management" },
    { match: "Security Hub", category: "Security", subcategory: "Security Posture Management" },
    { match: "Macie", category: "Security", subcategory: "Security Posture Management" },
    { match: "Key Management Service", category: "Security", subcategory: "Secret Management" },
    { match: "Secrets Manager", category: "Security", subcategory: "Secret Management" },
    { match: "CloudHSM", category: "Security", subcategory: "Secret Management" },
    { match: "Certificate Manager", category: "Security", subcategory: "Other (Security)" },
    { match: "Cognito", category: "Identity", subcategory: "Identity and Access Management" },
    {
      match: "Directory Service",
      category: "Identity",
      subcategory: "Identity and Access Management",
    },
    {
      match: "IAM Identity Center",
      category: "Identity",
      subcategory: "Identity and Access Management",
    },
    { match: "CloudWatch", category: "Management and Governance", subcategory: "Observability" },
    { match: "X-Ray", category: "Management and Governance", subcategory: "Observability" },
    { match: "CloudTrail", category: "Management and Governance", subcategory: "Compliance" },
    { match: "AWS Config", category: "Management and Governance", subcategory: "Compliance" },
    { match: "Audit Manager", category: "Management and Governance", subcategory: "Compliance" },
    {
      match: "Systems Manager",
      category: "Management and Governance",
      subcategory: "Endpoint Management",
    },
    {
      match: "Cost Explorer",
      category: "Management and Governance",
      subcategory: "Cost Management",
    },
    {
      match: "Savings Plans",
      category: "Management and Governance",
      subcategory: "Cost Management",
    },
    { match: "Support", category: "Management and Governance", subcategory: "Support" },
    {
      match: "CodeBuild",
      category: "Developer Tools",
      subcategory: "Continuous Integration and Deployment",
    },
    {
      match: "CodePipeline",
      category: "Developer Tools",
      subcategory: "Continuous Integration and Deployment",
    },
    {
      match: "CodeDeploy",
      category: "Developer Tools",
      subcategory: "Continuous Integration and Deployment",
    },
    { match: "CodeCommit", category: "Developer Tools", subcategory: "Source Code Management" },
    { match: "CodeArtifact", category: "Developer Tools", subcategory: "Developer Platforms" },
    { match: "Cloud9", category: "Developer Tools", subcategory: "Development Environments" },
    { match: "Device Farm", category: "Developer Tools", subcategory: "Quality Assurance" },
    { match: "Amplify", category: "Web", subcategory: "Application Platforms" },
    { match: "Elastic Beanstalk", category: "Web", subcategory: "Application Platforms" },
    { match: "IoT", category: "Internet of Things", subcategory: "IoT Platforms" },
    { match: "Elemental", category: "Media", subcategory: "Media Streaming" },
    { match: "Interactive Video Service", category: "Media", subcategory: "Media Streaming" },
    { match: "Elastic Transcoder", category: "Media", subcategory: "Content Creation" },
    { match: "GameLift", category: "Media", subcategory: "Gaming" },
    { match: "Database Migration Service", category: "Migration", subcategory: "Data Migration" },
    { match: "DataSync", category: "Migration", subcategory: "Data Migration" },
    { match: "Transfer Family", category: "Migration", subcategory: "Data Migration" },
    {
      match: "Application Migration Service",
      category: "Migration",
      subcategory: "Resource Migration",
    },
    { match: "Outposts", category: "Compute", subcategory: "Other (Compute)" },
  ],
};
