import type {
  TerraformExportCapability,
  TerraformExportResult,
  TerraformValue,
} from "@infrawrench/plugin-base";
import { fieldBool, fieldNumber, fieldString, tf } from "@infrawrench/plugin-base";
import { EVENT_DESTINATION, METER, PRICE, PRODUCT, WEBHOOK_ENDPOINT } from "./resource-types.js";

/**
 * Terraform mapping for Stripe's official provider `stripe/stripe`
 * (https://github.com/stripe/terraform-provider-stripe, v0.3.0, generated by
 * Stripe from the API spec; attribute names checked against its `docs/`):
 *
 * - `stripe_webhook_endpoint`: `url`, `enabled_events` required; `description`,
 *   `api_version`, `connect` optional. `secret` is read-only and only known at
 *   creation, so an imported endpoint never has it.
 * - `stripe_product`: `name` required; `active`, `description`, `unit_label`,
 *   `statement_descriptor`, `tax_code`, `url` optional.
 * - `stripe_price`: `currency` required; `product`, `unit_amount`, `nickname`,
 *   `lookup_key`, `tax_behavior`, `active`, `recurring {}` block.
 *   Tiered and customer-chosen prices carry nested data the inventory does not
 *   keep, so they are reported as unsupported rather than exported wrong.
 * - `stripe_billing_meter`: `display_name`, `event_name` required;
 *   `default_aggregation {}`, `customer_mapping {}`, `value_settings {}`
 *   blocks, `event_time_window`.
 * - `stripe_v2_core_event_destination`: `name`, `type`, `event_payload`,
 *   `enabled_events` required; `webhook_endpoint {}` / `amazon_eventbridge {}`.
 *
 * Every import id is the Stripe object id. The key is `var.stripe_api_key`.
 */
export const stripeTerraformExport: TerraformExportCapability = {
  provider: { name: "stripe", source: "stripe/stripe", version: "~> 0.3" },
  providerConfig: { api_key: tf.ref("var.stripe_api_key") },
  variables: [
    {
      name: "stripe_api_key",
      description: "Stripe secret or restricted API key",
      sensitive: true,
    },
  ],
  supportedResourceTypeIds: [WEBHOOK_ENDPOINT, PRODUCT, PRICE, METER, EVENT_DESTINATION],
  mapResource(resource): TerraformExportResult | null {
    const importId = resource.externalId;
    const opt = (attrs: Record<string, TerraformValue>, key: string, value: string) => {
      if (value) attrs[key] = tf.str(value);
    };
    switch (resource.resourceTypeId) {
      case WEBHOOK_ENDPOINT: {
        const url = fieldString(resource, "url");
        const events = splitList(fieldString(resource, "enabledEvents"));
        if (!url || events.length === 0) return null;
        const attributes: Record<string, TerraformValue> = {
          url: tf.str(url),
          enabled_events: tf.list(events.map(tf.str)),
        };
        opt(attributes, "description", fieldString(resource, "description"));
        opt(attributes, "api_version", fieldString(resource, "apiVersion"));
        if (fieldBool(resource, "connect")) attributes["connect"] = tf.bool(true);
        return {
          resource: {
            type: "stripe_webhook_endpoint",
            name: fieldString(resource, "description") || resource.displayName,
            attributes,
            ...(importId ? { importId } : {}),
            comments: [
              "The signing secret is only returned when Terraform creates the endpoint; an imported endpoint keeps its existing secret.",
            ],
          },
        };
      }
      case PRODUCT: {
        const name = fieldString(resource, "name");
        if (!name) return null;
        const attributes: Record<string, TerraformValue> = { name: tf.str(name) };
        opt(attributes, "description", fieldString(resource, "description"));
        opt(attributes, "unit_label", fieldString(resource, "unitLabel"));
        opt(attributes, "statement_descriptor", fieldString(resource, "statementDescriptor"));
        opt(attributes, "tax_code", fieldString(resource, "taxCode"));
        opt(attributes, "url", fieldString(resource, "url"));
        if (resource.fields["active"] === false) attributes["active"] = tf.bool(false);
        return {
          resource: {
            type: "stripe_product",
            name,
            attributes,
            ...(importId ? { importId } : {}),
          },
        };
      }
      case PRICE: {
        const currency = fieldString(resource, "currency").toLowerCase();
        const scheme = fieldString(resource, "billingScheme");
        const unitAmount = fieldNumber(resource, "unitAmount");
        if (!currency || scheme === "tiered" || unitAmount === undefined) return null;
        const attributes: Record<string, TerraformValue> = {
          currency: tf.str(currency),
          unit_amount: tf.num(unitAmount),
        };
        opt(attributes, "product", fieldString(resource, "productId"));
        opt(attributes, "nickname", fieldString(resource, "nickname"));
        opt(attributes, "lookup_key", fieldString(resource, "lookupKey"));
        const tax = fieldString(resource, "taxBehavior");
        if (tax && tax !== "unspecified") attributes["tax_behavior"] = tf.str(tax);
        if (resource.fields["active"] === false) attributes["active"] = tf.bool(false);
        const interval = fieldString(resource, "interval");
        if (interval) {
          const recurring: Record<string, TerraformValue> = { interval: tf.str(interval) };
          const count = fieldNumber(resource, "intervalCount");
          if (count && count > 1) recurring["interval_count"] = tf.num(count);
          const usage = fieldString(resource, "usageType");
          if (usage) recurring["usage_type"] = tf.str(usage);
          const meter = fieldString(resource, "meterId");
          if (meter) recurring["meter"] = tf.str(meter);
          attributes["recurring"] = tf.block(recurring);
        }
        return {
          resource: {
            type: "stripe_price",
            name: resource.displayName,
            attributes,
            ...(importId ? { importId } : {}),
            comments: ["Stripe prices are immutable: changing an amount creates a new price."],
          },
        };
      }
      case METER: {
        const displayName = fieldString(resource, "displayName");
        const eventName = fieldString(resource, "eventName");
        if (!displayName || !eventName) return null;
        const attributes: Record<string, TerraformValue> = {
          display_name: tf.str(displayName),
          event_name: tf.str(eventName),
        };
        const formula = fieldString(resource, "aggregation");
        if (formula) attributes["default_aggregation"] = tf.block({ formula: tf.str(formula) });
        const customerKey = fieldString(resource, "customerPayloadKey");
        if (customerKey) {
          attributes["customer_mapping"] = tf.block({
            event_payload_key: tf.str(customerKey),
            type: tf.str("by_id"),
          });
        }
        const valueKey = fieldString(resource, "valuePayloadKey");
        if (valueKey) {
          attributes["value_settings"] = tf.block({ event_payload_key: tf.str(valueKey) });
        }
        opt(attributes, "event_time_window", fieldString(resource, "eventTimeWindow"));
        return {
          resource: {
            type: "stripe_billing_meter",
            name: displayName,
            attributes,
            ...(importId ? { importId } : {}),
          },
        };
      }
      case EVENT_DESTINATION: {
        const name = fieldString(resource, "name");
        const type = fieldString(resource, "type");
        const payload = fieldString(resource, "eventPayload");
        const events = splitList(fieldString(resource, "enabledEvents"));
        if (!name || !type || !payload || events.length === 0) return null;
        const attributes: Record<string, TerraformValue> = {
          name: tf.str(name),
          type: tf.str(type),
          event_payload: tf.str(payload),
          enabled_events: tf.list(events.map(tf.str)),
        };
        opt(attributes, "description", fieldString(resource, "description"));
        opt(attributes, "snapshot_api_version", fieldString(resource, "snapshotApiVersion"));
        const from = splitList(fieldString(resource, "eventsFrom"));
        if (from.length > 0) attributes["events_from"] = tf.list(from.map(tf.str));
        if (type === "webhook_endpoint") {
          const url = fieldString(resource, "url");
          if (!url) return null;
          attributes["webhook_endpoint"] = tf.block({ url: tf.str(url) });
        } else if (type === "amazon_eventbridge") {
          attributes["amazon_eventbridge"] = tf.block({
            aws_account_id: tf.str(fieldString(resource, "awsAccountId")),
            aws_region: tf.str(fieldString(resource, "awsRegion")),
          });
        } else if (type === "azure_event_grid") {
          // An attribute (not a block) in the provider schema.
          attributes["azure_event_grid"] = tf.map({
            azure_region: tf.str(fieldString(resource, "azureRegion")),
            azure_resource_group_name: tf.str(fieldString(resource, "azureResourceGroup")),
            azure_subscription_id: tf.str(fieldString(resource, "azureSubscriptionId")),
          });
        } else {
          return null;
        }
        return {
          resource: {
            type: "stripe_v2_core_event_destination",
            name,
            attributes,
            ...(importId ? { importId } : {}),
          },
        };
      }
      default:
        return null;
    }
  },
};

function splitList(value: string): string[] {
  return value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}
