/**
 * The wire format of the web edge Worker's plugin registry
 * (`plugin-registry-edge.gen.json`): every bundled plugin as plain data, with
 * each function replaced by a marker naming where it was.
 *
 * Kept generic on purpose: nothing here knows which members a plugin has.
 * `manifest` and `resourceTypes` are already pure data; `createClient`,
 * `parseStatusFeed`, `terraformExport.mapResource` and the rest become
 * markers, which `plugin-registry-edge.ts` revives as functions that throw
 * the gateway-only error, so a capability check (`if (plugin.policyTemplate)`)
 * answers exactly as it does on Node and only *calling* one hands the request
 * to the gateway.
 */
import type { Plugin } from "@infrawrench/plugin-base";

export const FUNCTION_MARKER = "$gatewayOnly";

export interface EdgePluginRegistryFile {
  $comment: string;
  plugins: unknown[];
}

function encode(value: unknown, path: string): unknown {
  if (typeof value === "function") return { [FUNCTION_MARKER]: path };
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map((v, i) => encode(v, `${path}[${i}]`));
  const out: Record<string, unknown> = {};
  for (const [key, v] of Object.entries(value)) {
    if (v !== undefined) out[key] = encode(v, `${path}.${key}`);
  }
  return out;
}

export function serializePluginsForEdge(plugins: readonly Plugin[]): EdgePluginRegistryFile {
  return {
    $comment:
      "Generated by `pnpm --filter @infrawrench/server-core generate:edge-plugins` from plugin-registry.ts. Do not edit; edge-plugin-registry.test.ts fails when it is stale.",
    plugins: plugins.map((p) => encode(p, p.manifest.id)),
  };
}
