import type { RegionOption } from "@infrawrench/plugin-base";

export const AZURE_REGIONS: RegionOption[] = [
  { id: "eastus", label: "East US", location: "Virginia, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  { id: "eastus2", label: "East US 2", location: "Virginia, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  { id: "westus", label: "West US", location: "California, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  { id: "westus2", label: "West US 2", location: "Washington, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  { id: "westus3", label: "West US 3", location: "Arizona, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  { id: "centralus", label: "Central US", location: "Iowa, USA", flag: "\u{1F1FA}\u{1F1F8}" },
  {
    id: "northcentralus",
    label: "North Central US",
    location: "Illinois, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
  },
  {
    id: "southcentralus",
    label: "South Central US",
    location: "Texas, USA",
    flag: "\u{1F1FA}\u{1F1F8}",
  },
  {
    id: "canadacentral",
    label: "Canada Central",
    location: "Toronto, Canada",
    flag: "\u{1F1E8}\u{1F1E6}",
  },
  {
    id: "canadaeast",
    label: "Canada East",
    location: "Quebec, Canada",
    flag: "\u{1F1E8}\u{1F1E6}",
  },
  { id: "northeurope", label: "North Europe", location: "Ireland", flag: "\u{1F1EE}\u{1F1EA}" },
  { id: "westeurope", label: "West Europe", location: "Netherlands", flag: "\u{1F1F3}\u{1F1F1}" },
  { id: "uksouth", label: "UK South", location: "London, UK", flag: "\u{1F1EC}\u{1F1E7}" },
  { id: "ukwest", label: "UK West", location: "Cardiff, UK", flag: "\u{1F1EC}\u{1F1E7}" },
  {
    id: "francecentral",
    label: "France Central",
    location: "Paris, France",
    flag: "\u{1F1EB}\u{1F1F7}",
  },
  {
    id: "germanywestcentral",
    label: "Germany West Central",
    location: "Frankfurt, Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
  },
  {
    id: "swedencentral",
    label: "Sweden Central",
    location: "Gävle, Sweden",
    flag: "\u{1F1F8}\u{1F1EA}",
  },
  { id: "norwayeast", label: "Norway East", location: "Oslo, Norway", flag: "\u{1F1F3}\u{1F1F4}" },
  {
    id: "switzerlandnorth",
    label: "Switzerland North",
    location: "Zürich, Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
  },
  { id: "eastasia", label: "East Asia", location: "Hong Kong", flag: "\u{1F1ED}\u{1F1F0}" },
  {
    id: "southeastasia",
    label: "Southeast Asia",
    location: "Singapore",
    flag: "\u{1F1F8}\u{1F1EC}",
  },
  { id: "japaneast", label: "Japan East", location: "Tokyo, Japan", flag: "\u{1F1EF}\u{1F1F5}" },
  { id: "japanwest", label: "Japan West", location: "Osaka, Japan", flag: "\u{1F1EF}\u{1F1F5}" },
  {
    id: "australiaeast",
    label: "Australia East",
    location: "Sydney, Australia",
    flag: "\u{1F1E6}\u{1F1FA}",
  },
  {
    id: "australiasoutheast",
    label: "Australia Southeast",
    location: "Melbourne, Australia",
    flag: "\u{1F1E6}\u{1F1FA}",
  },
  {
    id: "koreacentral",
    label: "Korea Central",
    location: "Seoul, South Korea",
    flag: "\u{1F1F0}\u{1F1F7}",
  },
  {
    id: "centralindia",
    label: "Central India",
    location: "Pune, India",
    flag: "\u{1F1EE}\u{1F1F3}",
  },
  {
    id: "southindia",
    label: "South India",
    location: "Chennai, India",
    flag: "\u{1F1EE}\u{1F1F3}",
  },
  {
    id: "brazilsouth",
    label: "Brazil South",
    location: "São Paulo, Brazil",
    flag: "\u{1F1E7}\u{1F1F7}",
  },
  {
    id: "southafricanorth",
    label: "South Africa North",
    location: "Johannesburg, South Africa",
    flag: "\u{1F1FF}\u{1F1E6}",
  },
  { id: "uaenorth", label: "UAE North", location: "Dubai, UAE", flag: "\u{1F1E6}\u{1F1EA}" },
  {
    id: "qatarcentral",
    label: "Qatar Central",
    location: "Doha, Qatar",
    flag: "\u{1F1F6}\u{1F1E6}",
  },
  {
    id: "polandcentral",
    label: "Poland Central",
    location: "Warsaw, Poland",
    flag: "\u{1F1F5}\u{1F1F1}",
  },
  { id: "italynorth", label: "Italy North", location: "Milan, Italy", flag: "\u{1F1EE}\u{1F1F9}" },
];
